<?php

// mapping of old categs to new ones
$categs = array(
    'Building',
    'Code Generation',
    'Databases',
    'Debugging',
    'Desktop Applications',
    'Distributed Applications',
    'Documentation',
    'Editing',
    'Enterprise Applications',
    'Fun Stuff',
    'Graphical User Interface',
    'Libraries',
    'Mobile Applications',
    'Modeling',
    'NetBeans Rich Client Platform',
    'Programming Languages',
    'Profiling',
    'Refactoring',
    'Testing',
    'Team Collaboration',
    'Utilities',
    'Version Control Systems',
    'Web Applications ',
    'Uncategorized'
);

$mapping = array(
    'Building' => 'Ant Visualizer',
    'Building' => 'Maven',
    'Other Development' => 'Code Generation',
    'Database 12' => 'Databases',
    'Plug-in' => 'Databases',
    'Debugging cc' => 'Debugging',
    'Debugging' => 'Debugging',
    'Java' => 'Desktop Applications',
    'Java SE' => 'Desktop Applications',
    'Developing OpenOffice.org' => 'Desktop Applications',
    'Developing VisualVM' => 'Desktop Applications',
    'Mozilla' => 'Desktop Applications',
    'Distributed Applications' => 'Distributed Applications',
    'Utility Computing' => 'Distributed Applications',
    'Documentation' => 'Documentation',
    'Help' => 'Documentation',
    'Localizations' => 'Documentation',
    'Web Services' => 'Documentation',
    'Editing' => 'Editing',
    'Editor' => 'Editing',
    'External Editor' => 'Editing',
    'LaTeX' => 'Editing',
    'Web Search' => 'Editing',
    'Java EE' => 'Enterprise Applications',
    'Java Web and EE' => 'Enterprise Applications',
    'SOA' => 'Enterprise Applications',
    'Visual Web' => 'Enterprise Applications',
    'Entertainment' => 'Fun Stuff',
    'Neural Network' => 'Fun Stuff',
    'Second Life' => 'Fun Stuff',
    'SunSPOTs' => 'Fun Stuff',
    'GUI' => 'Graphical User Interface',
    'NetBeans Layout Pack' => 'Graphical User Interface',
    'Libraries' => 'Libraries',
    'MDR' => 'Libraries',
    'Infrastructure' => 'Libraries',
    'J2ME' => 'Mobile Applications',
    'Wireless Access' => 'Mobile Applications',
    'Java ME' => 'Mobile Applications',
    'Mobility' => 'Mobile Applications',
    'Modeling' => 'Modeling',
    'HyperData' => 'Modeling',
    'Developing NetBeans' => 'NetBeans Rich Client Platform',
    'Base IDE' => 'NetBeans Rich Client Platform',
    'IDE' => 'NetBeans Rich Client Platform',
    'NetBeans RCP' => 'NetBeans Rich Client Platform',
    'C++' => 'Programming Languages',
    'C/C++' => 'Programming Languages',
    'Fortran' => 'Programming Languages',
    'Java' => 'Programming Languages',
    'JavaFX' => 'Programming Languages',
    'Javascript' => 'Programming Languages',
    'Scripting Languages' => 'Programming Languages',
    'Agent Factory' => 'Programming Languages',
    'Clojure' => 'Programming Languages',
    'COCO/R' => 'Programming Languages',
    'Fantom' => 'Programming Languages',
    'Languages Support' => 'Programming Languages',
    'PHP' => 'Programming Languages',
    'Scripting' => 'Programming Languages',
    'Profiling' => 'Profiling',
    'Developing VisualVM' => 'Profiling',
    'Refactoring' => 'Refactoring',
    'Test Tools' => 'Testing',
    'Testing Tools' => 'Testing',
    'Distributed Development' => 'Team Collaboration',
    'Remote Development' => 'Team Collaboration',
    'Collaboration' => 'Team Collaboration',
    'Uncategorised' => 'Team Collaboration',
    'Infrastructure' => 'Utilities',
    'Tools' => 'Utilities',
    'd.max' => 'Utilities',
    'Data Files' => 'Utilities',
    'Platform' => 'Utilities',
    'System Administration' => 'Utilities',
    'Task List' => 'Utilities',
    'Utilities' => 'Utilities',
    'Experimental' => 'Utilities',
    'Version Control' => 'Version Control Systems',
    'Versioning' => 'Version Control Systems',
    'XML' => 'Web Applications',
    'Adds action to comment/uncomment JSP & XML' => 'Web Applications',
    'HTML' => 'Web Applications',
    'Mildda' => 'Web Applications',
    'Mobile Web Applications' => 'Web Applications',
    'Web' => 'Web Applications',
    'Web & Java EE' => 'Web Applications',
    'Web Applications' => 'Web Applications',
    'Capture'=>'Uncategorized',
    'Features'=>'Uncategorized',
    'Ayuda'=>'Uncategorized',
);
?>