package org.netbeans.test.xml.schema.general.dtd;

import java.util.Calendar;

public class data
{
  private static String sDay = ( ( Calendar.getInstance( ).get( Calendar.DAY_OF_MONTH ) < 10 ) ? "0" : "" ) + Calendar.getInstance( ).get( Calendar.DAY_OF_MONTH );
  private static String sMonth = ( ( ( Calendar.getInstance( ).get( Calendar.MONTH ) + 1 ) < 10 ) ? "0" : "" ) + ( Calendar.getInstance( ).get( Calendar.MONTH ) + 1 );
  private static String sYear = ( ( Calendar.getInstance( ).get( Calendar.YEAR ) < 10 ) ? "0" : "" ) + Calendar.getInstance( ).get( Calendar.YEAR );

  public static String sIdealDocumentation = "<!DOCTYPEhtmlPUBLIC\"-//W3C//DTDXHTML1.0Strict//EN\"\"http://www.w3."
+ "org/TR/xhtml1/DTD/xhtml1-strict.dtd\"><html><head><title>DTDGrammarDocumentation<"
+ "/title><metahttp-equiv=\"Content-Type\"content=\"text/xhtml;charset=UTF-8\"/></head>"
+ "<!--Generatedon" + sDay + "." + sMonth + "." + sYear + "byNetBeansXMLmodule.--><body><hr/><h2>ElementIndex</h2>"
+ "<ul><li><tt><ahref=\"#ns0:USPrice\">ns0:USPrice</a></tt></li><li><tt><ahref=\"#ns0:"
+ "billTo\">ns0:billTo</a></tt></li><li><tt><ahref=\"#ns0:city\">ns0:city</a></tt></li"
+ "><li><tt><ahref=\"#ns0:comment\">ns0:comment</a></tt></li><li><tt><ahref=\"#ns0:ite"
+ "m\">ns0:item</a></tt></li><li><tt><ahref=\"#ns0:items\">ns0:items</a></tt></li><li>"
+ "<tt><ahref=\"#ns0:name\">ns0:name</a></tt></li><li><tt><ahref=\"#ns0:productName\">n"
+ "s0:productName</a></tt></li><li><tt><ahref=\"#ns0:purchaseOrder\">ns0:purchaseOrde"
+ "r</a></tt></li><li><tt><ahref=\"#ns0:quantity\">ns0:quantity</a></tt></li><li><tt>"
+ "<ahref=\"#ns0:shipDate\">ns0:shipDate</a></tt></li><li><tt><ahref=\"#ns0:shipTo\">ns"
+ "0:shipTo</a></tt></li><li><tt><ahref=\"#ns0:state\">ns0:state</a></tt></li><li><tt"
+ "><ahref=\"#ns0:street\">ns0:street</a></tt></li><li><tt><ahref=\"#ns0:zip\">ns0:zip<"
+ "/a></tt></li></ul><hr/><h2>ElementDetails</h2><hr/><h2><aname=\"ns0:purchaseOrder"
+ "\"></a>ns0:purchaseOrder</h2><div>PutyourDTDDoccommenthere.</div><p><b>DeclaredAt"
+ "tributes</b></p><ul><li><tt>#IMPLIEDCDATAxsi:schemaLocation</tt></li><li><tt>#IM"
+ "PLIEDCDATAxmlns:ns0</tt></li><li><tt>#IMPLIEDCDATAxmlns:xsi</tt></li><li><tt>#IM"
+ "PLIEDCDATAorderDate</tt></li></ul><p><b>ElementContentModel</b></p><p><tt>(<ahre"
+ "f=\"#ns0:shipTo\">ns0:shipTo</a>&nbsp;|<ahref=\"#ns0:comment\">ns0:comment</a>&nbsp;"
+ "|<ahref=\"#ns0:billTo\">ns0:billTo</a>&nbsp;|<ahref=\"#ns0:items\">ns0:items</a>)*</"
+ "tt></p><p><b>Referencedby</b></p><p><tt></tt></p><hr/><h2><aname=\"ns0:shipTo\"></"
+ "a>ns0:shipTo</h2><div>PutyourDTDDoccommenthere.</div><p><b>DeclaredAttributes</b"
+ "></p><ul><li><tt>#IMPLIEDCDATAcountry</tt></li></ul><p><b>ElementContentModel</b"
+ "></p><p><tt>(<ahref=\"#ns0:city\">ns0:city</a>&nbsp;|<ahref=\"#ns0:name\">ns0:name</"
+ "a>&nbsp;|<ahref=\"#ns0:state\">ns0:state</a>&nbsp;|<ahref=\"#ns0:street\">ns0:street"
+ "</a>&nbsp;|<ahref=\"#ns0:zip\">ns0:zip</a>)*</tt></p><p><b>Referencedby</b></p><p>"
+ "<tt><ahref=\"#ns0:purchaseOrder\">ns0:purchaseOrder</a></tt></p><hr/><h2><aname=\"n"
+ "s0:name\"></a>ns0:name</h2><div>PutyourDTDDoccommenthere.</div><p><b>ElementConte"
+ "ntModel</b></p><p><tt>EMPTY</tt></p><p><b>Referencedby</b></p><p><tt><ahref=\"#ns"
+ "0:shipTo\">ns0:shipTo</a>,<ahref=\"#ns0:billTo\">ns0:billTo</a></tt></p><hr/><h2><a"
+ "name=\"ns0:street\"></a>ns0:street</h2><div>PutyourDTDDoccommenthere.</div><p><b>E"
+ "lementContentModel</b></p><p><tt>EMPTY</tt></p><p><b>Referencedby</b></p><p><tt>"
+ "<ahref=\"#ns0:shipTo\">ns0:shipTo</a>,<ahref=\"#ns0:billTo\">ns0:billTo</a></tt></p>"
+ "<hr/><h2><aname=\"ns0:city\"></a>ns0:city</h2><div>PutyourDTDDoccommenthere.</div>"
+ "<p><b>ElementContentModel</b></p><p><tt>EMPTY</tt></p><p><b>Referencedby</b></p>"
+ "<p><tt><ahref=\"#ns0:shipTo\">ns0:shipTo</a>,<ahref=\"#ns0:billTo\">ns0:billTo</a></"
+ "tt></p><hr/><h2><aname=\"ns0:state\"></a>ns0:state</h2><div>PutyourDTDDoccommenthe"
+ "re.</div><p><b>ElementContentModel</b></p><p><tt>EMPTY</tt></p><p><b>Referencedb"
+ "y</b></p><p><tt><ahref=\"#ns0:shipTo\">ns0:shipTo</a>,<ahref=\"#ns0:billTo\">ns0:bil"
+ "lTo</a></tt></p><hr/><h2><aname=\"ns0:zip\"></a>ns0:zip</h2><div>PutyourDTDDoccomm"
+ "enthere.</div><p><b>ElementContentModel</b></p><p><tt>EMPTY</tt></p><p><b>Refere"
+ "ncedby</b></p><p><tt><ahref=\"#ns0:shipTo\">ns0:shipTo</a>,<ahref=\"#ns0:billTo\">ns"
+ "0:billTo</a></tt></p><hr/><h2><aname=\"ns0:billTo\"></a>ns0:billTo</h2><div>Putyou"
+ "rDTDDoccommenthere.</div><p><b>DeclaredAttributes</b></p><ul><li><tt>#IMPLIEDCDA"
+ "TAcountry</tt></li></ul><p><b>ElementContentModel</b></p><p><tt>(<ahref=\"#ns0:ci"
+ "ty\">ns0:city</a>&nbsp;|<ahref=\"#ns0:name\">ns0:name</a>&nbsp;|<ahref=\"#ns0:state\""
+ ">ns0:state</a>&nbsp;|<ahref=\"#ns0:street\">ns0:street</a>&nbsp;|<ahref=\"#ns0:zip\""
+ ">ns0:zip</a>)*</tt></p><p><b>Referencedby</b></p><p><tt><ahref=\"#ns0:purchaseOrd"
+ "er\">ns0:purchaseOrder</a></tt></p><hr/><h2><aname=\"ns0:comment\"></a>ns0:comment<"
+ "/h2><div>PutyourDTDDoccommenthere.</div><p><b>ElementContentModel</b></p><p><tt>"
+ "EMPTY</tt></p><p><b>Referencedby</b></p><p><tt><ahref=\"#ns0:purchaseOrder\">ns0:p"
+ "urchaseOrder</a>,<ahref=\"#ns0:item\">ns0:item</a></tt></p><hr/><h2><aname=\"ns0:it"
+ "ems\"></a>ns0:items</h2><div>PutyourDTDDoccommenthere.</div><p><b>ElementContentM"
+ "odel</b></p><p><tt>(<ahref=\"#ns0:item\">ns0:item</a>)*</tt></p><p><b>Referencedby"
+ "</b></p><p><tt><ahref=\"#ns0:purchaseOrder\">ns0:purchaseOrder</a></tt></p><hr/><h"
+ "2><aname=\"ns0:item\"></a>ns0:item</h2><div>PutyourDTDDoccommenthere.</div><p><b>D"
+ "eclaredAttributes</b></p><ul><li><tt>#IMPLIEDCDATApartNum</tt></li></ul><p><b>El"
+ "ementContentModel</b></p><p><tt>(<ahref=\"#ns0:shipDate\">ns0:shipDate</a>&nbsp;|<"
+ "ahref=\"#ns0:comment\">ns0:comment</a>&nbsp;|<ahref=\"#ns0:USPrice\">ns0:USPrice</a>"
+ "&nbsp;|<ahref=\"#ns0:quantity\">ns0:quantity</a>&nbsp;|<ahref=\"#ns0:productName\">n"
+ "s0:productName</a>)*</tt></p><p><b>Referencedby</b></p><p><tt><ahref=\"#ns0:items"
+ "\">ns0:items</a></tt></p><hr/><h2><aname=\"ns0:productName\"></a>ns0:productName</h"
+ "2><div>PutyourDTDDoccommenthere.</div><p><b>ElementContentModel</b></p><p><tt>EM"
+ "PTY</tt></p><p><b>Referencedby</b></p><p><tt><ahref=\"#ns0:item\">ns0:item</a></tt"
+ "></p><hr/><h2><aname=\"ns0:quantity\"></a>ns0:quantity</h2><div>PutyourDTDDoccomme"
+ "nthere.</div><p><b>ElementContentModel</b></p><p><tt>EMPTY</tt></p><p><b>Referen"
+ "cedby</b></p><p><tt><ahref=\"#ns0:item\">ns0:item</a></tt></p><hr/><h2><aname=\"ns0"
+ ":USPrice\"></a>ns0:USPrice</h2><div>PutyourDTDDoccommenthere.</div><p><b>ElementC"
+ "ontentModel</b></p><p><tt>EMPTY</tt></p><p><b>Referencedby</b></p><p><tt><ahref="
+ "\"#ns0:item\">ns0:item</a></tt></p><hr/><h2><aname=\"ns0:shipDate\"></a>ns0:shipDate"
+ "</h2><div>PutyourDTDDoccommenthere.</div><p><b>ElementContentModel</b></p><p><tt"
+ ">EMPTY</tt></p><p><b>Referencedby</b></p><p><tt><ahref=\"#ns0:item\">ns0:item</a><"
+ "/tt></p></body></html>";
}
