package org.netbeans.test.xml.schema.general.dtd;

import java.util.Calendar;

public class data
{
  private static String sDay = ( ( Calendar.getInstance( ).get( Calendar.DAY_OF_MONTH ) < 10 ) ? "0" : "" ) + Calendar.getInstance( ).get( Calendar.DAY_OF_MONTH );
  private static String sMonth = ( ( ( Calendar.getInstance( ).get( Calendar.MONTH ) + 1 ) < 10 ) ? "0" : "" ) + ( Calendar.getInstance( ).get( Calendar.MONTH ) + 1 );
  private static String sYear = ( ( Calendar.getInstance( ).get( Calendar.YEAR ) < 10 ) ? "0" : "" ) + Calendar.getInstance( ).get( Calendar.YEAR );

  public static String sIdealDocumentation =

"<!DOCTYPEhtmlPUBLIC\"-//W3C//DTDXHTML1.0Strict//EN\"\"http://www.w3"
+ ".org/TR/xhtml1/DTD/xhtml1-strict.dtd\"><html><head><title>DTDGrammarDocumentation"
+ "</title><metahttp-equiv=\"Content-Type\"content=\"text/xhtml;charset=UTF-8\"/></head"
+ "><!--Generatedon" + sDay + "." + sMonth + "." + sYear + "byNetBeansXMLmodule.--><body><hr/><h2>ElementIndex</h2"
+ "><ul><li><tt><ahref=\"#ns0:USPrice\">ns0:USPrice</a></tt></li><li><tt><ahref=\"#ns0"
+ ":billTo\">ns0:billTo</a></tt></li><li><tt><ahref=\"#ns0:city\">ns0:city</a></tt></l"
+ "i><li><tt><ahref=\"#ns0:comment\">ns0:comment</a></tt></li><li><tt><ahref=\"#ns0:it"
+ "em\">ns0:item</a></tt></li><li><tt><ahref=\"#ns0:items\">ns0:items</a></tt></li><li"
+ "><tt><ahref=\"#ns0:name\">ns0:name</a></tt></li><li><tt><ahref=\"#ns0:productName\">"
+ "ns0:productName</a></tt></li><li><tt><ahref=\"#ns0:purchaseOrder\">ns0:purchaseOrd"
+ "er</a></tt></li><li><tt><ahref=\"#ns0:quantity\">ns0:quantity</a></tt></li><li><tt"
+ "><ahref=\"#ns0:shipDate\">ns0:shipDate</a></tt></li><li><tt><ahref=\"#ns0:shipTo\">n"
+ "s0:shipTo</a></tt></li><li><tt><ahref=\"#ns0:state\">ns0:state</a></tt></li><li><t"
+ "t><ahref=\"#ns0:street\">ns0:street</a></tt></li><li><tt><ahref=\"#ns0:zip\">ns0:zip"
+ "</a></tt></li></ul><hr/><h2>ElementDetails</h2><hr/><h2><aname=\"ns0:purchaseOrde"
+ "r\"></a>ns0:purchaseOrder</h2><div>PutyourDTDDoccommenthere.</div><p><b>DeclaredA"
+ "ttributes</b></p><ul><li><tt>#IMPLIEDCDATAxsi:schemaLocation</tt></li><li><tt>#I"
+ "MPLIEDCDATAxmlns:ns0</tt></li><li><tt>#IMPLIEDCDATAxmlns:xsi</tt></li><li><tt>#I"
+ "MPLIEDCDATAorderDate</tt></li></ul><p><b>ElementContentModel</b></p><p><tt>(<ahr"
+ "ef=\"#ns0:shipTo\">ns0:shipTo</a>&nbsp;|<ahref=\"#ns0:comment\">ns0:comment</a>&nbsp"
+ ";|<ahref=\"#ns0:billTo\">ns0:billTo</a>&nbsp;|<ahref=\"#ns0:items\">ns0:items</a>)*<"
+ "/tt></p><p><b>Referencedby</b></p><p><tt></tt></p><hr/><h2><aname=\"ns0:shipTo\"><"
+ "/a>ns0:shipTo</h2><div>PutyourDTDDoccommenthere.</div><p><b>DeclaredAttributes</"
+ "b></p><ul><li><tt>#IMPLIEDCDATAcountry</tt></li></ul><p><b>ElementContentModel</"
+ "b></p><p><tt>(<ahref=\"#ns0:city\">ns0:city</a>&nbsp;|<ahref=\"#ns0:name\">ns0:name<"
+ "/a>&nbsp;|<ahref=\"#ns0:state\">ns0:state</a>&nbsp;|<ahref=\"#ns0:street\">ns0:stree"
+ "t</a>&nbsp;|<ahref=\"#ns0:zip\">ns0:zip</a>)*</tt></p><p><b>Referencedby</b></p><p"
+ "><tt><ahref=\"#ns0:purchaseOrder\">ns0:purchaseOrder</a></tt></p><hr/><h2><aname=\""
+ "ns0:name\"></a>ns0:name</h2><div>PutyourDTDDoccommenthere.</div><p><b>ElementCont"
+ "entModel</b></p><p><tt>EMPTY</tt></p><p><b>Referencedby</b></p><p><tt><ahref=\"#n"
+ "s0:shipTo\">ns0:shipTo</a>,<ahref=\"#ns0:billTo\">ns0:billTo</a></tt></p><hr/><h2><"
+ "aname=\"ns0:street\"></a>ns0:street</h2><div>PutyourDTDDoccommenthere.</div><p><b>"
+ "ElementContentModel</b></p><p><tt>EMPTY</tt></p><p><b>Referencedby</b></p><p><tt"
+ "><ahref=\"#ns0:shipTo\">ns0:shipTo</a>,<ahref=\"#ns0:billTo\">ns0:billTo</a></tt></p"
+ "><hr/><h2><aname=\"ns0:city\"></a>ns0:city</h2><div>PutyourDTDDoccommenthere.</div"
+ "><p><b>ElementContentModel</b></p><p><tt>EMPTY</tt></p><p><b>Referencedby</b></p"
+ "><p><tt><ahref=\"#ns0:shipTo\">ns0:shipTo</a>,<ahref=\"#ns0:billTo\">ns0:billTo</a><"
+ "/tt></p><hr/><h2><aname=\"ns0:state\"></a>ns0:state</h2><div>PutyourDTDDoccommenth"
+ "ere.</div><p><b>ElementContentModel</b></p><p><tt>EMPTY</tt></p><p><b>Referenced"
+ "by</b></p><p><tt><ahref=\"#ns0:shipTo\">ns0:shipTo</a>,<ahref=\"#ns0:billTo\">ns0:bi"
+ "llTo</a></tt></p><hr/><h2><aname=\"ns0:zip\"></a>ns0:zip</h2><div>PutyourDTDDoccom"
+ "menthere.</div><p><b>ElementContentModel</b></p><p><tt>EMPTY</tt></p><p><b>Refer"
+ "encedby</b></p><p><tt><ahref=\"#ns0:shipTo\">ns0:shipTo</a>,<ahref=\"#ns0:billTo\">n"
+ "s0:billTo</a></tt></p><hr/><h2><aname=\"ns0:billTo\"></a>ns0:billTo</h2><div>Putyo"
+ "urDTDDoccommenthere.</div><p><b>DeclaredAttributes</b></p><ul><li><tt>#IMPLIEDCD"
+ "ATAcountry</tt></li></ul><p><b>ElementContentModel</b></p><p><tt>(<ahref=\"#ns0:c"
+ "ity\">ns0:city</a>&nbsp;|<ahref=\"#ns0:name\">ns0:name</a>&nbsp;|<ahref=\"#ns0:state"
+ "\">ns0:state</a>&nbsp;|<ahref=\"#ns0:street\">ns0:street</a>&nbsp;|<ahref=\"#ns0:zip"
+ "\">ns0:zip</a>)*</tt></p><p><b>Referencedby</b></p><p><tt><ahref=\"#ns0:purchaseOr"
+ "der\">ns0:purchaseOrder</a></tt></p><hr/><h2><aname=\"ns0:comment\"></a>ns0:comment"
+ "</h2><div>PutyourDTDDoccommenthere.</div><p><b>ElementContentModel</b></p><p><tt"
+ ">EMPTY</tt></p><p><b>Referencedby</b></p><p><tt><ahref=\"#ns0:purchaseOrder\">ns0:"
+ "purchaseOrder</a>,<ahref=\"#ns0:item\">ns0:item</a></tt></p><hr/><h2><aname=\"ns0:i"
+ "tems\"></a>ns0:items</h2><div>PutyourDTDDoccommenthere.</div><p><b>ElementContent"
+ "Model</b></p><p><tt>(<ahref=\"#ns0:item\">ns0:item</a>)*</tt></p><p><b>Referencedb"
+ "y</b></p><p><tt><ahref=\"#ns0:purchaseOrder\">ns0:purchaseOrder</a></tt></p><hr/><"
+ "h2><aname=\"ns0:item\"></a>ns0:item</h2><div>PutyourDTDDoccommenthere.</div><p><b>"
+ "DeclaredAttributes</b></p><ul><li><tt>#IMPLIEDCDATApartNum</tt></li></ul><p><b>E"
+ "lementContentModel</b></p><p><tt>(<ahref=\"#ns0:shipDate\">ns0:shipDate</a>&nbsp;|"
+ "<ahref=\"#ns0:comment\">ns0:comment</a>&nbsp;|<ahref=\"#ns0:USPrice\">ns0:USPrice</a"
+ ">&nbsp;|<ahref=\"#ns0:quantity\">ns0:quantity</a>&nbsp;|<ahref=\"#ns0:productName\">"
+ "ns0:productName</a>)*</tt></p><p><b>Referencedby</b></p><p><tt><ahref=\"#ns0:item"
+ "s\">ns0:items</a></tt></p><hr/><h2><aname=\"ns0:productName\"></a>ns0:productName</"
+ "h2><div>PutyourDTDDoccommenthere.</div><p><b>ElementContentModel</b></p><p><tt>E"
+ "MPTY</tt></p><p><b>Referencedby</b></p><p><tt><ahref=\"#ns0:item\">ns0:item</a></t"
+ "t></p><hr/><h2><aname=\"ns0:quantity\"></a>ns0:quantity</h2><div>PutyourDTDDoccomm"
+ "enthere.</div><p><b>ElementContentModel</b></p><p><tt>EMPTY</tt></p><p><b>Refere"
+ "ncedby</b></p><p><tt><ahref=\"#ns0:item\">ns0:item</a></tt></p><hr/><h2><aname=\"ns"
+ "0:USPrice\"></a>ns0:USPrice</h2><div>PutyourDTDDoccommenthere.</div><p><b>Element"
+ "ContentModel</b></p><p><tt>EMPTY</tt></p><p><b>Referencedby</b></p><p><tt><ahref"
+ "=\"#ns0:item\">ns0:item</a></tt></p><hr/><h2><aname=\"ns0:shipDate\"></a>ns0:shipDat"
+ "e</h2><div>PutyourDTDDoccommenthere.</div><p><b>ElementContentModel</b></p><p><t"
+ "t>EMPTY</tt></p><p><b>Referencedby</b></p><p><tt><ahref=\"#ns0:item\">ns0:item</a>"
+ "</tt></p></body></html>";

}
