# Mac OS X makefile

#
# The contents of this file are subject to the terms of the Common Development
# and Distribution License (the License). You may not use this file except in
# compliance with the License.
#
# You can obtain a copy of the License at http://www.netbeans.org/cddl.html
# or http://www.netbeans.org/cddl.txt.
#
# When distributing Covered Code, include this CDDL Header Notice in each file
# and include the License file at http://www.netbeans.org/cddl.txt.
# If applicable, add the following below the CDDL Header, with the fields
# enclosed by brackets [] replaced by your own identifying information:
# "Portions Copyrighted [year] [name of copyright owner]"
#
# The Original Software is NetBeans. The Initial Developer of the Original
# Software is Sun Microsystems, Inc. Portions Copyright 1997-2006 Sun
# Microsystems, Inc. All Rights Reserved.
#


# change to your location of JDK
JAVA_HOME=/Library/Java/Home

# you might need to change 'i386' to your architecture when
# compiling on non x86 machines
# you can get your architecture from java system property 'os.arch'
LIBRARY_NAME=lib.jnikill.macosx.ppc.dylib


# you should not change anything below this line

INCLUDES=-I$(JAVA_HOME)/include/
CC=gcc
CFLAGS=

# fi


killer: org_netbeans_xtest_util_JNIKill.o
	$(CC) $(CFLAGS) -dynamiclib org_netbeans_xtest_util_JNIKill.o -o $(LIBRARY_NAME)

org_netbeans_xtest_util_JNIKill.o: \
	org_netbeans_xtest_util_JNIKill.c \
	org_netbeans_xtest_util_JNIKill.h

	$(CC) $(INCLUDES) $(CFLAGS) -c org_netbeans_xtest_util_JNIKill.c

clean:
	rm org_netbeans_xtest_util_JNIKill.o
	rm $(LIBRARY_NAME)
