<?xml version="1.0" encoding="UTF-8"?>
<definitions name="jdbcwsdl" targetNamespace="http://j2ee.netbeans.org/wsdl/jdbcbc"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
    xmlns:tns="http://j2ee.netbeans.org/wsdl/jdbcbc" 
    xmlns:ns="http://j2ee.netbeans.org/xsd/tableSchema"
    xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:jdbc="http://schemas.sun.com/jbi/wsdl-extensions/jdbc/">
    <types>
	<xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/jdbcbc">
            <xsd:import namespace="http://j2ee.netbeans.org/xsd/tableSchema" schemaLocation="jdbc.xsd.template"/>
	</xsd:schema>
    </types>
    <message name="inputMsg">
        <part name="part" element="ns:newuntitled_Request"/>
    </message>
    <message name="outputMsg">
        <part name="part" element="ns:newuntitled_Response"/>
    </message>
    <portType name="jdbcPortType">
        <operation name="newuntitled_Operation">
            <input name="input" message="tns:inputMsg"/>
	    <output name="output" message="tns:outputMsg"/>
        </operation>	
    </portType>
    <binding name="binding" type="tns:jdbcPortType">
        <jdbc:binding/>
        <operation name="newuntitled_Operation">
            <jdbc:operation/>
            <input name="input">
               <jdbc:input operationType="newuntitled_Operation" numberOfRecords="1" paramOrder="specify param order" sql="sqlQuery" PKName="testID" PollMilliSeconds="" Transaction="XATransaction" MarkColumnValue="2" PollingPostProcessing="MoveRow" TableName="APP.TestOutbound" MarkColumnName="testFlag" MoveRowToTableName="TestTable"/>
            </input>
	    <output name="output">
                <jdbc:output returnPartName="part"/>
            </output>
         </operation>	 
    </binding>
    <service name="service">
        <port name="port" binding="tns:binding">
            <jdbc:address jndiName="jndiname"/>
        </port>
    </service>
    <plink:partnerLinkType name="jdbcpartner">
        <plink:role name="jdbcPortTypeRole" portType="tns:jdbcPortType"/>
    </plink:partnerLinkType>
</definitions>