#!/bin/sh

# The contents of this file are subject to the terms of the Common Development
# and Distribution License (the License). You may not use this file except in
# compliance with the License.

# You can obtain a copy of the License at http://www.netbeans.org/cddl.html
# or http://www.netbeans.org/cddl.txt.

# When distributing Covered Code, include this CDDL Header Notice in each file
# and include the License file at http://www.netbeans.org/cddl.txt.
# If applicable, add the following below the CDDL Header, with the fields
# enclosed by brackets [] replaced by your own identifying information:
# "Portions Copyrighted [year] [name of copyright owner]"

# The Original Software is NetBeans. The Initial Developer of the Original
# Software is Sun Microsystems, Inc. Portions Copyright 1997-2007 Sun
# Microsystems, Inc. All Rights Reserved.

set -e

script_dir=`dirname "$0"`
source_dir=$1
target_dir=$2


jdk_home=`"$script_dir"/get_current_jdk.sh`

. "$script_dir"/env.sh

"$script_dir"/add_gfv3.sh "$NETBEANS_INSTALL_DIR" "$target_dir"

"$script_dir"/add_javadb.sh "$NETBEANS_INSTALL_DIR" "$target_dir/javadb"

"$script_dir"/perm.sh "$target_dir"

#add Product ID
"$script_dir"/addproduct_id.sh "GFMOD"
