<div id="conbox">
    <div id="skip" class="none"><a name="skip"></a></div>
    <div id="con">
        <h1>Contacts</h1>
        <p>In case of any questions or issues don't hesitate to contact PHP 
            NetBeans team on community mailing list 
            <a href="mailto:users@php.netbeans.org">users@php.netbeans.org</a>
        </p>
        <p>You can submit a bug on 
            <a href="http://netbeans.org/bugzilla/enter_bug.cgi?product=php">
                http://netbeans.org/bugzilla/enter_bug.cgi?product=php
            </a>.
        </p>
        <p>Or if you want, you can contact me directly on fzamboj [at] netbeans [dot] org.
            <br>I'm looking forward to hearing from you. 
        </p>
        
        <p><br><br> <strong>Regards, <br><br> Your NetBeans PHP Team<br> Prague, Czech Republic <strong></p>

    </div>
</div>
