#!/bin/sh -x

# The contents of this file are subject to the terms of the Common Development
# and Distribution License (the License). You may not use this file except in
# compliance with the License.

# You can obtain a copy of the License at http://www.netbeans.org/cddl.html
# or http://www.netbeans.org/cddl.txt.

# When distributing Covered Code, include this CDDL Header Notice in each file
# and include the License file at http://www.netbeans.org/cddl.txt.
# If applicable, add the following below the CDDL Header, with the fields
# enclosed by brackets [] replaced by your own identifying information:
# "Portions Copyrighted [year] [name of copyright owner]"

# The Original Software is NetBeans. The Initial Developer of the Original
# Software is Sun Microsystems, Inc. Portions Copyright 1997-2007 Sun
# Microsystems, Inc. All Rights Reserved.

set -e

dirname=`dirname "$0"`

. "$dirname"/env.sh

#add Product ID
"$dirname"/addproduct_id.sh "MOB"

#clean receipts
"$dirname"/clean_receipts.sh "javame-$NB_ID" "org.netbeans.ide.javame"

#Workaround. Having .app in the data results in TokenDefinitions.plist been created in the package
#and IFPkgPathMappings added to Info.plist in the .pkg. That results in error during installation for some reason.
cd "$NETBEANS_INSTALL_DIR"/Contents/Resources/NetBeans*/mobility/Java_ME_platform_SDK_3.0
mv Updaterapp Updater.app
mv device-managerapp device-manager.app
