#!/bin/sh

ANT_OPTS='-Xmx512m -XX:MaxPermSize=128m'
export ANT_OPTS

if [ -d contrib/.hg ] ; then
    hg -R contrib pull -u
else
    hg clone http://hg.netbeans.org/main/contrib contrib
fi

if [ builds/`ls -1 ../builds | tail -2 | head -1` '!=' `readlink ../lastSuccessful` ]
then
    echo "Previous build failed, running clean build this time..."
    ant -f nbbuild/build.xml hg-clean || exit
fi

mydir=`cd $(dirname $0)/..; pwd`
keystore=$mydir/NBstore
storepass=`cat $mydir/storepass`
ant -emacs -Dbuildnum=$BUILD_TAG -Dcluster.config=experimental -Dmoduleconfig=daily-alpha-nbms -Dkeystore=$keystore -Dstorepass=$storepass -f nbbuild/build.xml build-nozip build-nbms || exit
ant -f core/test/build.xml -Dxtest.attribs=commit cleanresults runtests || exit
ant -f nbbuild/build.xml -Dtest.dir=`pwd`/core/test commit-validation-junit-format || exit
ant -v -f $mydir/build-update-descriptor.xml || exit
ant -f nbbuild/build.xml -Djnlp.codebase=http://deadlock.netbeans.org/hudson/job/javadoc-nbms/lastSuccessfulBuild/artifact/nbbuild/build/jnlp/ -Djnlp.signjar.keystore=$keystore -Djnlp.signjar.alias=nb_ide -Djnlp.signjar.password=$storepass build-jnlp || exit
ant -f nbbuild/build.xml index-layer-paths
ant -f nbbuild/build.xml clean-untracked-files
