#!/bin/sh

[ -n "$push_username" ] || exit 102
[ -n "$push_password" ] || exit 103
[ -n "$push_repo" ] || exit 104

rollback() {
  EXIT="$?"
  if [ -n "$BASETIP" ]; then
    echo "Script failed with exitcode $EXIT rolling back to $BASETIP"
    hg heads
    hg update -C
    hg --config extensions.mq= strip -n "$BASETIP"
    hg pull -r "$BASETIP"
  else
    echo "No rollback, exitcode $EXIT"
  fi
}

BASETIP=`hg log -r . --template '{node}'`
trap rollback EXIT

hg pull -u http://hg.netbeans.org/"$push_repo"

HEADS=`hg heads --template "{node} XX{branches}XX\n" | grep XXXX | cut -f 1 -d ' ' | wc -l`
if [ $HEADS = 2 ]; then
    echo "2 heads, Need to merge"
    hg --config ui.merge=internal:merge --config ui.interactive=1 merge < /dev/null || exit 8
    hg ci -u "$push_username"@netbeans.org -m "Automated merge with main-silver"
else
    if [ $HEADS -gt 2 ]; then
        echo "$HEADS heads, here is some diagnostic"
        hg heads
    fi
fi

TIP=`hg log -r . --template '{node}'`

if hg push -r $TIP https://"$push_username":"$push_password"@hg.netbeans.org/"$push_repo"; then
    echo Push OK.
else
    HEADS=`hg heads --template "{node} XX{branches}XX\n" | grep XXXX | cut -f 1 -d ' ' | wc -l`
    hg incoming http://hg.netbeans.org/"$push_repo"
    STATUS=$?
    # status is 1 when there are no incoming changesets
    if [ "$HEADS" = 1 ] && [ "$STATUS" = 1 ]; then
        hg push -f -r $TIP https://"$push_username":"$push_password"@hg.netbeans.org/"$push_repo" || exit 9
    else
        echo Too many heads $HEADS in default branch or there are some incoming changesets $STATUS
        exit 9
    fi
fi
unset BASETIP
exit 0
