#!/bin/sh

[ -n "$push_username" ] || exit 102
[ -n "$push_password" ] || exit 103
[ -n "$push_repo" ] || exit 104
HGMERGE=merge
export HGMERGE

rollback() {
  EXIT="$?"
  if [ -n "$BASETIP" ]; then
    echo "Script failed with exitcode $EXIT rolling back to $BASETIP"
    hg update -C
    hg --config extensions.mq= strip -n "$BASETIP"
    hg pull -r "$BASETIP"
  else
    echo "No rollback, exitcode $EXIT"
  fi
}

BASETIP=`hg id -i | tr -d "+"`
trap rollback EXIT

hg pull -u "$push_username"@netbeans.org http://hg.netbeans.org/"$push_repo"

HEADS=`hg heads --template "{node}\n" | wc -l`
if [ $HEADS = 2 ]; then
    echo "2 heads, Need to merge"
    hg merge || exit 8
    hg ci -m "Automated merge with main-silver"
else if [ $HEADS -qt 2 ]; then
   echo "$HEADS heads, here is some diagnostic"
   hg heads
fi

hg push https://"$push_username":"$push_password"@hg.netbeans.org/"$push_repo" || exit 9
unset BASETIP
exit 0
