#!/bin/sh

rm -rf nbbuild/netbeans/ nbrubyide applemenu netbeans.png netbeans.icns conf
unzip -d nbbuild/ ../../trunk/lastSuccessful/archive/nbbuild/NetBeans-hudson-trunk-*.zip

source nbbuild/hudson/ruby-applemenu

cp nbbuild/netbeans/nb6.0/netbeans.icns nbbuild/netbeans/nb6.0/netbeans.png .

mkdir core
ant -f scripting/ruby/build.xml clean build-zip && \
    ant -Dnbplatform.default.netbeans.dest.dir=$PWD/nbbuild/netbeans \
        -Dnbplatform.default.harness.dir=$PWD/nbbuild/netbeans/harness \
        -f scripting/ruby/rubyide/build.xml clean build-zip && \
    mv scripting/ruby/netbeans-ruby.zip scripting/ruby/netbeans-ruby-hudson-${BUILD_NUMBER}.zip && \
    mv scripting/ruby/rubyide/dist/nbrubyide.zip scripting/ruby/rubyide/dist/netbeans-rubyide-hudson-${BUILD_NUMBER}.zip && \
    source nbbuild/hudson/ruby-etcconf

rm -rf nbrubyide netbeans.icns netbeans.png conf

