#!/bin/sh

# Make some modifications to the netbeans.conf configuration file (to insert apple menubar, and some other flags used in NetBeans)
# Also add in a Mac dock icon

unzip ruby/rubyide/dist/netbeans-rubyide-hudson-${BUILD_NUMBER}.zip nbrubyide/etc/nbrubyide.conf && \
cat nbrubyide/etc/nbrubyide.conf | sed 's/-J-Xms24m -J-Xmx384m -J-Xmx64m/-J-client -J-Xss2m -J-Xms32m -J-XX:PermSize=32m -J-XX:MaxPermSize=200m -J-Dapple.laf.useScreenMenuBar=true/' > nbrubyide.conf.patched && \
mv nbrubyide.conf.patched nbrubyide/etc/nbrubyide.conf && \
zip ruby/rubyide/dist/netbeans-rubyide-hudson-${BUILD_NUMBER}.zip nbrubyide/etc/nbrubyide.conf && \
unzip ruby/rubyide/dist/netbeans-rubyide-hudson-${BUILD_NUMBER}.zip nbrubyide/bin/nbrubyide && \
cat nbrubyide/bin/nbrubyide | sed "s/Xdock:name='\"\$APPNAME\"'/Xdock:name=RubyNetBeans \"-J-Xdock:icon=\$progdir\/..\/nb6.5\/netbeans.icns\"/g" | sed 's/$APPNAME/nbrubyide/' > nbrubyide.patched && \
mv nbrubyide.patched nbrubyide/bin/nbrubyide && \
chmod ugo+x nbrubyide/bin/nbrubyide && \
zip ruby/rubyide/dist/netbeans-rubyide-hudson-${BUILD_NUMBER}.zip nbrubyide/bin/nbrubyide && \
mkdir -p nbrubyide/nb6.5 && \
cp netbeans.icns netbeans.png nbrubyide/nb6.5 && \
zip ruby/rubyide/dist/netbeans-rubyide-hudson-${BUILD_NUMBER}.zip nbrubyide/nb6.5/netbeans.icns nbrubyide/nb6.5/netbeans.png && \
rm -rf nbrubyide netbeans.icns netbeans.png

