#!/bin/sh
rm -rf nbbuild/netbeans/
unzip -d nbbuild/ ../../trunk/lastSuccessful/archive/nbbuild/NetBeans-hudson-trunk-*.zip
mkdir core
ant -f scripting/ruby/build.xml clean build-zip && \
    ant -Dnbplatform.default.harness.dir=$PWD/nbbuild/netbeans/harness -f scripting/ruby/rubyide/build.xml clean build-zip \
    mv scripting/ruby/netbeans-ruby.zip scripting/ruby/netbeans-ruby-hudson-${BUILD_NUMBER}.zip \
    mv scripting/ruby/rubyide/dist/nbrubyide.zip scripting/ruby/rubyide/dist/netbeans-rubyide-hudson-${BUILD_NUMBER}.zip
