#!/bin/sh
ant -f nbbuild/build.xml cvs-clean || exit
#ant -f nbbuild/build.xml checkout || exit
ant -f nbbuild/build.xml build-nozip || exit
ant -f xtest/build.xml || exit
ant -f nbbuild/build.xml build-test-dist
