<?php
/*
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 *
 * Copyright 1997-2010 Oracle and/or its affiliates. All rights reserved.
 *
 * Oracle and Java are registered trademarks of Oracle and/or its affiliates.
 * Other names may be trademarks of their respective owners.
 *
 * The contents of this file are subject to the terms of either the GNU
 * General Public License Version 2 only ("GPL") or the Common
 * Development and Distribution License("CDDL") (collectively, the
 * "License"). You may not use this file except in compliance with the
 * License. You can obtain a copy of the License at
 * http://www.netbeans.org/cddl-gplv2.html
 * or nbbuild/licenses/CDDL-GPL-2-CP. See the License for the
 * specific language governing permissions and limitations under the
 * License.  When distributing the software, include this License Header
 * Notice in each file and include the License file at
 * nbbuild/licenses/CDDL-GPL-2-CP.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the GPL Version 2 section of the License file that
 * accompanied this code. If applicable, add the following below the
 * License Header, with the fields enclosed by brackets [] replaced by
 * your own identifying information:
 * "Portions Copyrighted [year] [name of copyright owner]"
 *
 * Contributor(s):
 *
 * The Original Software is NetBeans. The Initial Developer of the Original
 * Software is Sun Microsystems, Inc. Portions Copyright 1997-2006 Sun
 * Microsystems, Inc. All Rights Reserved.
 *
 * If you wish your version of this file to be governed by only the CDDL
 * or only the GPL Version 2, indicate your decision by adding
 * "[Contributor] elects to include this software in this distribution
 * under the [CDDL or GPL Version 2] license." If you do not indicate a
 * single choice of license, a recipient has the option to distribute
 * your version of this file under either the CDDL, the GPL Version 2 or
 * to extend the choice of license to its licensees as provided above.
 * However, if you add GPL Version 2 code and therefore, elected the GPL
 * Version 2 license, then the option applies only if the new code is
 * made subject to such option by the copyright holder.
 */
?>
<div id="conbox">
    <div id="skip" class="none"><a name="skip"></a></div>
    <div id="con">
        <h1>My Favorites</h1>

        <div id ="list">
            <?php echo $this->noResultsMessage ?>

            <?php foreach ($this->properties as $property): ?>
                <div class="result" id="p<?= $property->getId() ?>">
                    <div class="text">
                        <h2>
                            <?php echo $property->getTitle_en() ?>
                            <?php foreach ($property->getLocation() as $location): ?>
                                , <?php echo $location->getCity(); ?>
                            <?php endforeach; ?>
                            , <?php echo $property->getArea() ?> m&sup2;
                        </h2>
                        <p><?php echo substr($property->getText_en(), 0, 200) ?> ...</p>
                        <p class="price"><?php echo $property->getFormattedPrice() ?><span> EUR</span></p>
                    </div> 
                    <br />
                        <p>
                            <a  class="fav-del" href="
                                <?php 
                                echo $this->url(array(
                                    "controller" => "my-favorites",
                                    "action" => "index",
                                    "removeFromFavorites" => $property->getId()
                                ));
                                ?>
                                " 
                                onclick="removeFromFavoritesInFavorites(<?= $property->getId() ?>)" 
                                title="Remove from favorites">Remove from favorites
                            </a>
                            &nbsp;&nbsp;
                            <a href="<?php echo $this->url(array("controller" => "property", "action" => "detail", "property" => $property->getId()), null, true); ?>">More</a>
                        </p>
                        
                    
                </div>
                <?php
                if ($res == 1) {
                    echo '<div class="cleaner hr"></div>';
                    $res = 0;
                } else {
                    $res++;
                }
                ?>
            <?php endforeach; ?>
        </div>
        <div class="cleaner hr"></div>
    </div>
</div>