#!/bin/sh
#set -x
tool_name=$(basename "$0")
case "$tool_name" in
    "cc" | "xgcc" | "clang" | "icc" | "gcc"*)
        tool=$__CND_C_TOOL__
        tool_path_variable="__CND_C_TOOL__"
        ;;
    "CC" | "c++" | "clang++" | "icpc" | "cl" | "g++"*)
        tool=$__CND_CPP_TOOL__
        tool_path_variable="__CND_CPP_TOOL__"
        ;;
esac
if [ -n "$tool" ]; then
    tool_path=`dirname ${tool}`
    PATH=${tool_path}:${PATH}
    PWD=`pwd`
    echo >> ${__CND_BUILD_LOG__}
    echo called: ${tool} >> ${__CND_BUILD_LOG__}
    echo "\t${PWD}" >> ${__CND_BUILD_LOG__}
    echo "\t${tool}" >> ${__CND_BUILD_LOG__}
    for opt in "$@"; do
        echo "\t${opt}" >> ${__CND_BUILD_LOG__}
    done
    echo ""
    exec ${tool} "$@"
fi
echo "Set path to $tool_name compiler in env variable $tool_path_variable"
exit -1
