#!/bin/sh -x

# The contents of this file are subject to the terms of the Common Development
# and Distribution License (the License). You may not use this file except in
# compliance with the License.

# You can obtain a copy of the License at http://www.netbeans.org/cddl.html
# or http://www.netbeans.org/cddl.txt.

# When distributing Covered Code, include this CDDL Header Notice in each file
# and include the License file at http://www.netbeans.org/cddl.txt.
# If applicable, add the following below the CDDL Header, with the fields
# enclosed by brackets [] replaced by your own identifying information:
# "Portions Copyrighted [year] [name of copyright owner]"

# The Original Software is NetBeans. The Initial Developer of the Original
# Software is Sun Microsystems, Inc. Portions Copyright 1997-2007 Sun
# Microsystems, Inc. All Rights Reserved.

set -e

#update netbeans.conf
script_dir=`dirname "$0"`

. "$script_dir"/env.sh

"$script_dir"/add_gf.sh "$NETBEANS_INSTALL_DIR" "$2"

"$script_dir"/unpack200.sh "$2" "$2"

cd "$2"

echo Configuring GlassFish in `pwd`

ant_bin=./lib/ant/bin/ant

java_exe=/System/Library/Frameworks/JavaVM.framework/Versions/1.5/Home/bin/java

getPort() {
   basePort=$1
   freePort=`$java_exe -jar "$script_dir"/getport.jar $basePort`
   echo $freePort
}

if [ -f $ant_bin ]
then
  echo Ant found:
  ls -l $ant_bin
  if ! [ -x $ant_bin ]
  then
    echo Making ant executable: $ant_bin
    chmod a+x $ant_bin
  fi

  admin_port=`getPort 4848`
  instance_port=`getPort 8080`
  orb_port=`getPort 3700`
  imq_port=`getPort 7676`
  https_port=`getPort 8181`

  $ant_bin -f setup.xml -Dadmin.port=$admin_port -Dinstance.port=$instance_port -Dorb.port=$orb_port -Dimq.port=$imq_port -Dhttps.port=$https_port
else
  echo No ant found: $ant_bin
fi

"$script_dir"/perm.sh

if [ -d "/Library/Receipts/glassfish.pkg" ] ; then
    rm -rf "/Library/Receipts/glassfish.pkg"
fi
