#!/bin/sh -x

# The contents of this file are subject to the terms of the Common Development
# and Distribution License (the License). You may not use this file except in
# compliance with the License.

# You can obtain a copy of the License at http://www.netbeans.org/cddl.html
# or http://www.netbeans.org/cddl.txt.

# When distributing Covered Code, include this CDDL Header Notice in each file
# and include the License file at http://www.netbeans.org/cddl.txt.
# If applicable, add the following below the CDDL Header, with the fields
# enclosed by brackets [] replaced by your own identifying information:
# "Portions Copyrighted [year] [name of copyright owner]"

# The Original Software is NetBeans. The Initial Developer of the Original
# Software is Sun Microsystems, Inc. Portions Copyright 1997-2007 Sun
# Microsystems, Inc. All Rights Reserved.

set -e

#update netbeans.conf
script_dir=`dirname "$0"`

. "$script_dir"/env.sh

"$script_dir"/add_gf.sh "$2/../$NETBEANS_INSTALL_DIR" "$2"

"$script_dir"/unpack200.sh "$2" "$2"

cd "$2"

echo Configuring GlassFish in `pwd`

ant_bin=./lib/ant/bin/ant

if [ -f $ant_bin ]
then
  echo Ant found:
  ls -l $ant_bin
  if ! [ -x $ant_bin ]
  then
    echo Making ant executable: $ant_bin
    chmod a+x $ant_bin
  fi
  $ant_bin -f setup.xml
else
  echo No ant found: $ant_bin
fi

