#!/bin/sh -x

# The contents of this file are subject to the terms of the Common Development
# and Distribution License (the License). You may not use this file except in
# compliance with the License.

# You can obtain a copy of the License at http://www.netbeans.org/cddl.html
# or http://www.netbeans.org/cddl.txt.

# When distributing Covered Code, include this CDDL Header Notice in each file
# and include the License file at http://www.netbeans.org/cddl.txt.
# If applicable, add the following below the CDDL Header, with the fields
# enclosed by brackets [] replaced by your own identifying information:
# "Portions Copyrighted [year] [name of copyright owner]"

# The Original Software is NetBeans. The Initial Developer of the Original
# Software is Sun Microsystems, Inc. Portions Copyright 1997-2007 Sun
# Microsystems, Inc. All Rights Reserved.

set -e

script_dir=`dirname "$0"`

"$script_dir"/unpack200.sh "$2" "$2"

cd "$2"
cd ..

glassfish_dir=`pwd`
# http://www.netbeans.org/issues/show_bug.cgi?id=125358
# run the jbi core installer first - temporary solution 
#mv "$glassfish_dir/addons/jbi-core-installer.jar" "$glassfish_dir/jbi-core-installer.jar"
#`"$script_dir"/get_current_jdk.sh`/bin/java -jar "$glassfish_dir/jbi-core-installer.jar" "$glassfish_dir" install
#rm "$glassfish_dir/jbi-core-installer.jar"

./bin/asadmin install-addon "$glassfish_dir/addons/jbi_components_installer.jar"

"$script_dir"/perm.sh

if [ -d "/Library/Receipts/openesb.pkg" ] ; then
    rm -rf "/Library/Receipts/openesb.pkg"
fi

