/*
 *                 Sun Public License Notice
 *
 * The contents of this file are subject to the Sun Public License
 * Version 1.0 (the "License"). You may not use this file except in
 * compliance with the License. A copy of the License is available at
 * http://www.sun.com/
 *
 * The Original Code is NetBeans. The Initial Developer of the Original
 * Code is Sun Microsystems, Inc. Portions Copyright 1997-2005 Sun
 * Microsystems, Inc. All Rights Reserved.
 */
package org.netbeans.modules.collab.ui;

import org.openide.*;
import org.openide.util.*;

import java.awt.Dialog;

import java.util.*;

import javax.swing.*;
import javax.swing.event.*;

import org.netbeans.modules.collab.*;


/**
 *
 * @author  sherylsu
 */
public class SelectConferenceForm extends javax.swing.JPanel implements ListSelectionListener {
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel matchesFoundLabel;

    // End of variables declaration//GEN-END:variables
    private String[] conversations;
    private DialogDescriptor descriptor;

    /** Creates new form SelectUser */
    public SelectConferenceForm(String[] conversations) {
        this.conversations = conversations;

        descriptor = new DialogDescriptor(
                this, NbBundle.getMessage(SelectConferenceForm.class, "TITLE_SelectConferenceForm")
            ); // NOI18N
        descriptor.setValid(false);

        initComponents();

        // Update the label
        matchesFoundLabel.setText(
            NbBundle.getMessage(
                SelectUserForm.class, "LBL_SelectConferenceForm_Num_Conf", // NOI18N
                new Integer(conversations.length)
            )
        );

        jList1.setListData(conversations);

        Vector v = new Vector();
        v.addAll(Arrays.asList(conversations));

        // TODO: TAF: We need Conversation to implement Comparator
        //		Collections.sort(v);
        ListModel model = new ListModel(jList1, v, false, true, false);

        ListRenderer renderer = new ListRenderer(model);
        jList1.setCellRenderer(renderer);
        jList1.setModel(model);
        jList1.addListSelectionListener(this);
    }

    public String[] getSelectedConversations() {
        Dialog dialog = DialogDisplayer.getDefault().createDialog(descriptor);

        try {
            dialog.show();

            if (descriptor.getValue() == DialogDescriptor.OK_OPTION) {
                int[] indices = jList1.getSelectedIndices();
                String[] result = new String[indices.length];

                for (int i = 0; i < indices.length; i++) {
                    int j = indices[i];
                    result[i] = conversations[j];
                }

                return result;
            } else {
                return null;
            }
        } finally {
            dialog.dispose();
        }
    }

    /**
     *
     *
     */
    protected void updateValidStatus() {
        descriptor.setValid(jList1.getModel().getSize() != 0);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() { //GEN-BEGIN:initComponents

        java.awt.GridBagConstraints gridBagConstraints;

        matchesFoundLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();

        setLayout(new java.awt.GridBagLayout());

        setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(5, 5, 5, 5)));
        matchesFoundLabel.setText(
            java.util.ResourceBundle.getBundle("org/netbeans/modules/collab/ui/Bundle").getString(
                "LBL_SelectConferenceForm_Num_Conf"
            )
        );
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(matchesFoundLabel, gridBagConstraints);

        jLabel2.setText(
            java.util.ResourceBundle.getBundle("org/netbeans/modules/collab/ui/Bundle").getString(
                "LBL_SelectConferenceForm_PleaseSelect"
            )
        );
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        add(jLabel2, gridBagConstraints);

        jList1.setPreferredSize(null);
        jScrollPane1.setViewportView(jList1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        add(jScrollPane1, gridBagConstraints);
    } //GEN-END:initComponents

    public void valueChanged(ListSelectionEvent e) {
        updateValidStatus();
    }
}
