<definitions targetNamespace="http://sun.com/echo"
             name="echo"
             xmlns:tns="http://sun.com/echo"
             xmlns:slnk1="http://schemas.xmlsoap.org/ws/2004/03/partner-link/"
             xmlns:tns0="http://sun.com/echo"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:file="http://sun.com/jbi/wsdl/file10"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/">
    <types>
        <xsd:schema targetNamespace="http://sun.com/echo"
                    xmlns:tns="http://sun.com/echo"
                    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                    xmlns="http://schemas.xmlsoap.org/wsdl/"
                    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                    xmlns:slnk="http://schemas.xmlsoap.org/ws/2002/07/service-link/">
            
                    <xsd:element name="item">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element type="xsd:string"
                                     name="value"></xsd:element>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
        </xsd:schema>
    </types>
    <message name="echo">
        <part name="part"
              element="tns:item"></part>
    </message>
    <portType name="echo">
        <operation name="echo">
            <fault message="tns:echo"></fault>
        </operation>
    </portType>
    <binding name="Binding"
             type="tns:echo">
        <soap:binding style="document"
                      transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="echo">
            <soap:operation soapAction="echo"/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="echo">
        <port name="port"
              binding="tns:Binding">
            <soap:address location="http://localhost:12010/echo"/>
        </port>
    </service>
    <plnk:partnerLinkType name="SLT"
                          xmlns:plnk="http://schemas.xmlsoap.org/ws/2004/03/partner-link/">
        <plnk:role name="server"
                   portType="tns:echo"></plnk:role>
    </plnk:partnerLinkType>
</definitions>
