#!/usr/bin/env ruby
@translations = {}
IO.foreach("#{File.dirname(File.expand_path(__FILE__))}/translations") do |line|
  from, to = line.chomp.split '//'
  @translations[from] = to.sub(%r{^main/}, '')
end
while gets do
  gsub!(%r{^(Index: |--- |\+\+\+ )(.+)/}) do |all|
    header = $1
    dir = $2
    suffix = ''
    if dir != '/dev' # /dev/null
      until @translations.has_key? dir
        if dir =~ %r{^(.+)(/[^/]+)$}
          dir = $1
          suffix = "#{$2}#{suffix}"
        else
          break
        end
      end
      if @translations.has_key? dir
        dir = @translations[dir]
      else
        dir = "XXX-new-location-unknown/#{dir}"
      end
    end
    "#{header}#{dir}#{suffix}/"
  end
  puts $_
end
