/*
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 *
 * Copyright 1997-2010 Oracle and/or its affiliates. All rights reserved.
 *
 * Oracle and Java are registered trademarks of Oracle and/or its affiliates.
 * Other names may be trademarks of their respective owners.
 *
 * The contents of this file are subject to the terms of either the GNU
 * General Public License Version 2 only ("GPL") or the Common
 * Development and Distribution License("CDDL") (collectively, the
 * "License"). You may not use this file except in compliance with the
 * License. You can obtain a copy of the License at
 * http://www.netbeans.org/cddl-gplv2.html
 * or nbbuild/licenses/CDDL-GPL-2-CP. See the License for the
 * specific language governing permissions and limitations under the
 * License.  When distributing the software, include this License Header
 * Notice in each file and include the License file at
 * nbbuild/licenses/CDDL-GPL-2-CP.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the GPL Version 2 section of the License file that
 * accompanied this code. If applicable, add the following below the
 * License Header, with the fields enclosed by brackets [] replaced by
 * your own identifying information:
 * "Portions Copyrighted [year] [name of copyright owner]"
 *
 * Contributor(s):
 *
 * The Original Software is NetBeans. The Initial Developer of the Original
 * Software is Sun Microsystems, Inc. Portions Copyright 1997-2006 Sun
 * Microsystems, Inc. All Rights Reserved.
 *
 * If you wish your version of this file to be governed by only the CDDL
 * or only the GPL Version 2, indicate your decision by adding
 * "[Contributor] elects to include this software in this distribution
 * under the [CDDL or GPL Version 2] license." If you do not indicate a
 * single choice of license, a recipient has the option to distribute
 * your version of this file under either the CDDL, the GPL Version 2 or
 * to extend the choice of license to its licensees as provided above.
 * However, if you add GPL Version 2 code and therefore, elected the GPL
 * Version 2 license, then the option applies only if the new code is
 * made subject to such option by the copyright holder.
 */


package org.netbeans.modules.deployment.deviceanywhere.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-04/12/2007 02:26 PM(vivekp)-RC1
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ApplicationAPI", targetNamespace = "http://services.mc.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ApplicationAPI {


    /**
     * 
     * @param jarFileData
     * @param password
     * @param jadFileData
     * @param appName
     * @param username
     * @return
     *     returns org.netbeans.modules.deployment.deviceanywhere.service.ApplicationAPIUploadApplicationReturn
     */
    @WebMethod
    @WebResult(name = "uploadApplicationReturn", targetNamespace = "http://services.mc.com")
    @RequestWrapper(localName = "uploadApplication", targetNamespace = "http://services.mc.com", className = "org.netbeans.modules.deployment.deviceanywhere.service.UploadApplication")
    @ResponseWrapper(localName = "uploadApplicationResponse", targetNamespace = "http://services.mc.com", className = "org.netbeans.modules.deployment.deviceanywhere.service.UploadApplicationResponse")
    public ApplicationAPIUploadApplicationReturn uploadApplication(
        @WebParam(name = "username", targetNamespace = "http://services.mc.com")
        String username,
        @WebParam(name = "password", targetNamespace = "http://services.mc.com")
        String password,
        @WebParam(name = "appName", targetNamespace = "http://services.mc.com")
        String appName,
        @WebParam(name = "jarFileData", targetNamespace = "http://services.mc.com")
        byte[] jarFileData,
        @WebParam(name = "jadFileData", targetNamespace = "http://services.mc.com")
        byte[] jadFileData);

    /**
     * 
     * @param password
     * @param username
     * @return
     *     returns org.netbeans.modules.deployment.deviceanywhere.service.ApplicationAPIGetLockedDevicesReturn
     */
    @WebMethod
    @WebResult(name = "getLockedDevicesReturn", targetNamespace = "http://services.mc.com")
    @RequestWrapper(localName = "getLockedDevices", targetNamespace = "http://services.mc.com", className = "org.netbeans.modules.deployment.deviceanywhere.service.GetLockedDevices")
    @ResponseWrapper(localName = "getLockedDevicesResponse", targetNamespace = "http://services.mc.com", className = "org.netbeans.modules.deployment.deviceanywhere.service.GetLockedDevicesResponse")
    public ApplicationAPIGetLockedDevicesReturn getLockedDevices(
        @WebParam(name = "username", targetNamespace = "http://services.mc.com")
        String username,
        @WebParam(name = "password", targetNamespace = "http://services.mc.com")
        String password);

    /**
     * 
     * @param password
     * @param deviceId
     * @param applicationId
     * @param username
     * @return
     *     returns org.netbeans.modules.deployment.deviceanywhere.service.ApplicationAPIStartDownloadScriptReturn
     */
    @WebMethod
    @WebResult(name = "startDownloadScriptReturn", targetNamespace = "http://services.mc.com")
    @RequestWrapper(localName = "startDownloadScript", targetNamespace = "http://services.mc.com", className = "org.netbeans.modules.deployment.deviceanywhere.service.StartDownloadScript")
    @ResponseWrapper(localName = "startDownloadScriptResponse", targetNamespace = "http://services.mc.com", className = "org.netbeans.modules.deployment.deviceanywhere.service.StartDownloadScriptResponse")
    public ApplicationAPIStartDownloadScriptReturn startDownloadScript(
        @WebParam(name = "username", targetNamespace = "http://services.mc.com")
        String username,
        @WebParam(name = "password", targetNamespace = "http://services.mc.com")
        String password,
        @WebParam(name = "deviceId", targetNamespace = "http://services.mc.com")
        int deviceId,
        @WebParam(name = "applicationId", targetNamespace = "http://services.mc.com")
        int applicationId);

}
