<?xml version="1.0" encoding="UTF-8"?>
<definitions name="InboundOneWayMessaging" targetNamespace="http://j2ee.netbeans.org/wsdl/BpelModule2/InboundOneWayMessaging"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/BpelModule2/InboundOneWayMessaging" xmlns:ftp="http://schemas.sun.com/jbi/wsdl-extensions/ftp/">
    <types/>
    <message name="InboundOneWayMessagingOperationRequest">
        <part name="part1" type="xsd:string"/>
    </message>
    <portType name="InboundOneWayMessagingPortType">
        <operation name="InboundOneWayMessagingOperation">
            <input name="input1" message="tns:InboundOneWayMessagingOperationRequest"/>
        </operation>
    </portType>
    <binding name="InboundOneWayMessagingBinding" type="tns:InboundOneWayMessagingPortType">
        <ftp:binding/>
        <operation name="InboundOneWayMessagingOperation">
            <ftp:operation/>
            <input name="input1">
                <ftp:message messageRepository="" messageName="" messageNamePrefixIB="" pollIntervalMillis="5000" archive="true" protect="true" stage="true" use="literal" encodingStyle=""/>
            </input>
        </operation>
    </binding>
    <service name="InboundOneWayMessagingService">
        <port name="#SERVICE_NAME_InboundOneWayMessagingPort" binding="tns:InboundOneWayMessagingBinding">
            <ftp:address url="ftp://anonymous:user\@yahoo.com@localhost:21" user="" password="" dirListStyle="UNIX" useUserDefinedHeuristics="false" userDefDirListStyle="" userDefDirListHeuristics="" mode="BINARY" securedFTP="None" enableCCC="false" keyStore="" keyStorePassword="" keyAlias="" keyPassword="" trustStore="" trustStorePassword="" cmdChannelTimeout="45000" dataChannelTimeout="45000"/>
        </port>
    </service>
</definitions>
