<?xml version="1.0" encoding="UTF-8"?>
<definitions name="InboundRequestResponseTransferring" targetNamespace="http://j2ee.netbeans.org/wsdl/BpelModule2/InboundRequestResponseTransferring"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/BpelModule2/InboundRequestResponseTransferring" xmlns:ftp="http://schemas.sun.com/jbi/wsdl-extensions/ftp/">
    <types/>
    <message name="InboundRequestResponseTransferringOperationRequest">
        <part name="part1" type="xsd:string"/>
    </message>
    <message name="InboundRequestResponseTransferringOperationResponse">
        <part name="part1" type="xsd:string"/>
    </message>
    <portType name="InboundRequestResponseTransferringPortType">
        <operation name="InboundRequestResponseTransferringOperation">
            <input name="input1" message="tns:InboundRequestResponseTransferringOperationRequest"/>
            <output name="output1" message="tns:InboundRequestResponseTransferringOperationResponse"/>
        </operation>
    </portType>
    <binding name="InboundRequestResponseTransferringBinding" type="tns:InboundRequestResponseTransferringPortType">
        <ftp:binding/>
        <operation name="InboundRequestResponseTransferringOperation">
            <ftp:operation/>
            <input name="input1">
                <ftp:transfer receiveFrom="" receiveFromHasRegexs="false" pollIntervalMillis="5000" preReceiveCommand="NONE" preReceiveLocation="" preReceiveLocationHasPatterns="false" postReceiveCommand="NONE" postReceiveLocation="" postReceiveLocationHasPatterns="false" use="literal" encodingStyle="" messageCorrelate="false"/>
            </input>
            <output name="output1">
                <ftp:transfer sendTo="" sendToHasPatterns="false" append="false" preSendCommand="NONE" preSendLocation="" preSendLocationHasPatterns="false" postSendCommand="NONE" postSendLocation="" postSendLocationHasPatterns="false" use="literal" encodingStyle="" messageCorrelate="false"/>
            </output>
        </operation>
    </binding>
    <service name="InboundRequestResponseTransferringService">
        <port name="#SERVICE_NAME_InboundRequestResponseTransferringPort" binding="tns:InboundRequestResponseTransferringBinding">
            <ftp:address url="ftp://anonymous:user\@yahoo.com@localhost:21" user="" password="" dirListStyle="UNIX" useUserDefinedHeuristics="false" userDefDirListStyle="" userDefDirListHeuristics="" mode="BINARY" securedFTP="None" enableCCC="false" keyStore="" keyStorePassword="" keyAlias="" keyPassword="" trustStore="" trustStorePassword="" cmdChannelTimeout="45000" dataChannelTimeout="45000"/>
        </port>
    </service>
</definitions>
