<?xml version="1.0" encoding="UTF-8"?>
<definitions name="ReceiveTransferring" targetNamespace="dummy"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="dummy" xmlns:ftp="http://schemas.sun.com/jbi/wsdl-extensions/ftp/">
    <types/>
    <message name="ReceiveTransferringOperationRequest">
    </message>
    <message name="ReceiveTransferringOperationResponse">
        <part name="part1" type="xsd:string"/>
    </message>
    <portType name="ReceiveTransferringPortType">
        <operation name="ReceiveTransferringOperation">
            <input name="input1" message="tns:ReceiveTransferringOperationRequest"/>
            <output name="output1" message="tns:ReceiveTransferringOperationResponse"/>
        </operation>
    </portType>
    <binding name="ReceiveTransferringPortTypeBinding" type="tns:ReceiveTransferringPortType">
        <ftp:binding/>
        <operation name="ReceiveTransferringOperation">
            <ftp:operation/>
            <input name="input1">
            </input>
            <output name="output1">
                <ftp:transfer receiveFrom="change_to_target_dir/change_to_target_file"/>
            </output>
        </operation>
    </binding>
    <service name="ReceiveTransferringService">
        <port name="#SERVICE_NAME_ReceiveTransferringPort" binding="tns:ReceiveTransferringPortTypeBinding">
            <ftp:address url="ftp://anonymous:user\@yahoo.com@localhost:21" user="" password="" dirListStyle="UNIX" useUserDefinedHeuristics="false" userDefDirListStyle="" userDefDirListHeuristics="" mode="BINARY" securedFTP="None" enableCCC="false" keyStore="" keyStorePassword="" keyAlias="" keyPassword="" trustStore="" trustStorePassword="" cmdChannelTimeout="45000" dataChannelTimeout="45000"/>
        </port>
    </service>
</definitions>
