/*
 * ExternalTableDatabaseTableColumnSelectionPanel.java
 *
 * Created on May 16, 2008, 3:09 PM
 */

package org.netbeans.modules.iep.editor.wizard.database.tableInput;

import java.awt.BorderLayout;
import java.util.List;
import org.netbeans.modules.iep.editor.wizard.database.ColumnInfo;
import org.netbeans.modules.iep.editor.wizard.database.DatabaseTableColumnSelectionPanel;
import org.netbeans.modules.iep.editor.wizard.database.TableInfo;

/**
 *
 * @author  radval
 */
public class ExternalTableDatabaseTableColumnSelectionPanel extends javax.swing.JPanel {

    private DatabaseTableColumnSelectionPanel mTableColumnSelectionPanel;
    
    /** Creates new form ExternalTableDatabaseTableColumnSelectionPanel */
    public ExternalTableDatabaseTableColumnSelectionPanel() {
        initComponents();
        
        mTableColumnSelectionPanel = new DatabaseTableColumnSelectionPanel();
        tableColumnSelectionPanelContainer.setLayout(new BorderLayout());
        tableColumnSelectionPanelContainer.add(mTableColumnSelectionPanel, BorderLayout.CENTER);
    }

    public void setSelectedTables(List<TableInfo> tables) {
        mTableColumnSelectionPanel.setSelectedTables(tables);
    }
    
    public List<ColumnInfo> getSelectedColumns() {
        return mTableColumnSelectionPanel.getSelectedColumns();
    }
    
    public String getJNDIName() {
        return jndiNameTextField.getText();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tableColumnSelectionPanelContainer = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jndiNameTextField = new javax.swing.JTextField();

        org.jdesktop.layout.GroupLayout tableColumnSelectionPanelContainerLayout = new org.jdesktop.layout.GroupLayout(tableColumnSelectionPanelContainer);
        tableColumnSelectionPanelContainer.setLayout(tableColumnSelectionPanelContainerLayout);
        tableColumnSelectionPanelContainerLayout.setHorizontalGroup(
            tableColumnSelectionPanelContainerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
        );
        tableColumnSelectionPanelContainerLayout.setVerticalGroup(
            tableColumnSelectionPanelContainerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 221, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Database Configuration"));

        jLabel3.setText("JNDI Name:"); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(jLabel3)
                .add(37, 37, 37)
                .add(jndiNameTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(jndiNameTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(tableColumnSelectionPanelContainer, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(tableColumnSelectionPanelContainer, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(11, 11, 11)
                .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jndiNameTextField;
    private javax.swing.JPanel tableColumnSelectionPanelContainer;
    // End of variables declaration//GEN-END:variables

}
