#!/bin/sh

# The contents of this file are subject to the terms of the Common Development
# and Distribution License (the License). You may not use this file except in
# compliance with the License.

# You can obtain a copy of the License at http://www.netbeans.org/cddl.html
# or http://www.netbeans.org/cddl.txt.

# When distributing Covered Code, include this CDDL Header Notice in each file
# and include the License file at http://www.netbeans.org/cddl.txt.
# If applicable, add the following below the CDDL Header, with the fields
# enclosed by brackets [] replaced by your own identifying information:
# "Portions Copyrighted [year] [name of copyright owner]"

# The Original Software is NetBeans. The Initial Developer of the Original
# Software is Sun Microsystems, Inc. Portions Copyright 1997-2007 Sun
# Microsystems, Inc. All Rights Reserved.

set -e

dirname=`dirname "$0"`

jdk_home=`"$dirname"/get_current_jdk.sh`

. "$dirname"/env.sh

"$dirname"/add_gfv3.sh "$NETBEANS_INSTALL_DIR" "$GLASSFISH_V3_INSTALL_DIR"

"$dirname"/add_javadb.sh "$NETBEANS_INSTALL_DIR" "$GLASSFISH_V3_INSTALL_DIR/javadb"

"$dirname"/add_tc.sh "$NETBEANS_INSTALL_DIR" "$TOMCAT_INSTALL_DIR"

if [ -f "$dirname"/set_jdk_home.sh ]; then
    "$dirname"/set_jdk_home.sh "$NETBEANS_INSTALL_DIR" "$DEFAULT_JDK7_HOME"
fi

"$dirname"/populate_caches.sh "$NETBEANS_INSTALL_DIR"
exit_code=$?
echo Result of populate_caches.sh : $exit_code

#fix for 114656
cd "$NETBEANS_INSTALL_DIR"
cd Contents/Resources/NetBeans*/${NB_CLUSTER_DIR}
mkdir -p var
touch var/license_accepted

#fix for 151681
"$dirname"/perm.sh "$NETBEANS_INSTALL_DIR"

#Fix for 151681
#Go to the /Application/NetBeans folder to change its permissions and ownership
chmod g+w "$NETBEANS_INSTALL_DIR"/..
chown root:wheel "$NETBEANS_INSTALL_DIR"/..

#add Product ID
"$dirname"/addproduct_id.sh "NB"
