#!/bin/sh -x

# The contents of this file are subject to the terms of the Common Development
# and Distribution License (the License). You may not use this file except in
# compliance with the License.

# You can obtain a copy of the License at http://www.netbeans.org/cddl.html
# or http://www.netbeans.org/cddl.txt.

# When distributing Covered Code, include this CDDL Header Notice in each file
# and include the License file at http://www.netbeans.org/cddl.txt.
# If applicable, add the following below the CDDL Header, with the fields
# enclosed by brackets [] replaced by your own identifying information:
# "Portions Copyrighted [year] [name of copyright owner]"

# The Original Software is NetBeans. The Initial Developer of the Original
# Software is Sun Microsystems, Inc. Portions Copyright 1997-2007 Sun
# Microsystems, Inc. All Rights Reserved.

set -e

dirname=`dirname "$0"`

jdk_home=`"$dirname"/get_current_jdk.sh`

. "$dirname"/env.sh

"$dirname"/unpack200.sh "$NETBEANS_INSTALL_DIR" "$NETBEANS_INSTALL_DIR/Contents/Resources/NetBeans" "$jdk_home"

"$dirname"/add_gf.sh "$NETBEANS_INSTALL_DIR" "$GLASSFISH_INSTALL_DIR"

"$dirname"/add_gfv3.sh "$NETBEANS_INSTALL_DIR" "$GLASSFISH_V3_INSTALL_DIR"

"$dirname"/add_javadb.sh "$NETBEANS_INSTALL_DIR" "$GLASSFISH_V3_INSTALL_DIR/javadb"

"$dirname"/add_tc.sh "$NETBEANS_INSTALL_DIR" "$TOMCAT_INSTALL_DIR"

"$dirname"/add_mysql.sh "$NETBEANS_INSTALL_DIR" "$MYSQL_INSTALL_DIR"

cd "$NETBEANS_INSTALL_DIR"
cd Contents/Resources/NetBeans*/etc
if [ -f netbeans.conf ]
then
  echo netbeans.conf found: `pwd`/netbeans.conf
## don't set netbeans_jdkhome: issue 159846 
#  if [ -d $jdk_home ] || [ -L $jdk_home ]
#  then
#    echo JDK home exists: $jdk_home
#    cp netbeans.conf netbeans.conf_orig_jdk_home
#    cat netbeans.conf_orig_jdk_home  | sed -e 's|.*netbeans_jdkhome.*|netbeans_jdkhome='$jdk_home'|' > netbeans.conf
#  else
#    echo No JDK home: $jdk_home
#  fi
  sed -E -i -e "s|\\$\{NETBEANS_HOME\}|$NETBEANS_INSTALL_DIR/Contents/Resources/NetBeans|g" netbeans.conf
else
  echo No netbeans.conf in: `pwd`
fi

#fix for 114656
cd "$NETBEANS_INSTALL_DIR"
cd Contents/Resources/NetBeans*/${NB_CLUSTER_DIR}
mkdir -p var
touch var/license_accepted

#fix for 151681
cd "$NETBEANS_INSTALL_DIR"
"$dirname"/perm.sh

#Fix for 151681
#Go to the /Application/NetBeans folder to change its permissions
cd ../
chmod g+w .

#add Product ID
"$dirname"/addproduct_id.sh "NB"

#clean receipts
"$dirname"/clean_receipts.sh "baseide-$NB_ID" "org.netbeans.ide.baseide"

#create ST for NB
"$dirname"/servicetag.sh "nb" "$2"

#Fix for 177872 (alternative: change Auth="None" for GF, but problem with existing root:admin dirs)
ownership=`ls -nlda ~ | awk ' { print $3 ":admin" } ' 2>/dev/null`
cd "$NETBEANS_INSTALL_DIR"/Contents/Resources/NetBeans*/"$NB_CLUSTER_DIR"
chown -R "$ownership" var servicetag
