#!/bin/sh -x

# The contents of this file are subject to the terms of the Common Development
# and Distribution License (the License). You may not use this file except in
# compliance with the License.

# You can obtain a copy of the License at http://www.netbeans.org/cddl.html
# or http://www.netbeans.org/cddl.txt.

# When distributing Covered Code, include this CDDL Header Notice in each file
# and include the License file at http://www.netbeans.org/cddl.txt.
# If applicable, add the following below the CDDL Header, with the fields
# enclosed by brackets [] replaced by your own identifying information:
# "Portions Copyrighted [year] [name of copyright owner]"

# The Original Software is NetBeans. The Initial Developer of the Original
# Software is Sun Microsystems, Inc. Portions Copyright 1997-2007 Sun
# Microsystems, Inc. All Rights Reserved.

set -e

basename=`dirname "$0"`
if [ -z "$basename" ]
then
    basename=.
fi
. "$basename"/env.sh

if [ -n "$NETBEANS_INSTALL_DIR" ] && [ -d "$NETBEANS_INSTALL_DIR" ] && [ 1 -eq "$NETBEANS_CHECK_BUILDNUMBER" ] ; then
    #read build_info to get current build number
    cd "$NETBEANS_INSTALL_DIR"/Contents/Resources/NetBeans/"$NB_CLUSTER_DIR";
    current_buildnumber=`cat build_info | sed '/Number/!d;s/Number:[ \t]*//'`
    if [ "$current_buildnumber" != "$NETBEANS_BUILDNUMBER" ] ; then
        backup_dir_name=`echo "$NETBEANS_INSTALL_DIR" | sed "s/\.app$/\_backup\.app/g"`
        [ -d "$backup_dir_name" ] && rm -rf "$backup_dir_name"
        mv -f "$NETBEANS_INSTALL_DIR" "$backup_dir_name"
    fi
fi


if [ -d "/Library/Receipts/baseide.pkg" ] ; then
    rm -rf "/Library/Receipts/baseide.pkg"
fi
