<definitions name="dummy" targetNamespace="dummy"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
    xmlns:tns="dummy" 
    xmlns:jms="http://schemas.sun.com/jbi/wsdl-extensions/jms/">
    <types/>   
    <message name="JMSInputMessage">
    </message>    
    <portType name="JMSInPortType">
        <operation name="JMSInOperation">
            <input name="input1" message="tns:JMSInputMessage"/>
        </operation>
    </portType>
    <binding name="JMSInBinding" type="tns:JMSInPortType">
        <jms:binding/>
        <operation name="JMSInOperation">
            <jms:operation destination="DefaultQueue" destinationType="Queue"/>
            <input name="input1">
                <jms:message messageType="TextMessage" textPart="change me"/>
            </input>
        </operation>
    </binding>
    <service name="JMSInService">
        <port name="#SERVICE_NAME_InPort" binding="tns:JMSInBinding">
            <jms:address connectionURL="lookup://jms/tx/default"/>
        </port>
    </service>
</definitions>
