<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://localhost:8080/axis/DecisionService.jws" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://localhost:8080/axis/DecisionService.jws" xmlns:intf="http://localhost:8080/axis/DecisionService.jws" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.2beta
Built on Jul 12, 2004 (07:08:50 EDT)-->

   <wsdl:message name="executeResponse">

   </wsdl:message>

   <wsdl:message name="executeRequest">

      <wsdl:part name="treeID" type="xsd:string"/>

      <wsdl:part name="batchID" type="xsd:int"/>

   </wsdl:message>

   <wsdl:portType name="DecisionService">

      <wsdl:operation name="execute" parameterOrder="treeID batchID">

         <wsdl:input message="impl:executeRequest" name="executeRequest"/>

         <wsdl:output message="impl:executeResponse" name="executeResponse"/>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="DecisionServiceSoapBinding" type="impl:DecisionService">

      <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="execute">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="executeRequest">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://DefaultNamespace" use="encoded"/>

         </wsdl:input>

         <wsdl:output name="executeResponse">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://localhost:8080/axis/DecisionService.jws" use="encoded"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="DecisionServiceService">

      <wsdl:port binding="impl:DecisionServiceSoapBinding" name="DecisionService">

         <wsdlsoap:address location="http://localhost:8080/axis/services/DecisionService"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
