<div id="admin-nav">
  <img src="<?= $this->baseUrl() ?>/images/icons/bullet_go.png" width="16" height="16" class="icon"/>&nbsp;<a href="<?= $this->baseUrl() ?>/admin/plugin-categories">Plugin Categories</a>
  <img src="<?= $this->baseUrl() ?>/images/icons/bullet_go.png" width="16" height="16" class="icon"/>&nbsp;<a href="<?= $this->baseUrl() ?>/admin/nb-versions">NetBeans Versions</a>
  <img src="<?= $this->baseUrl() ?>/images/icons/bullet_go.png" width="16" height="16" class="icon"/>&nbsp;<a href="<?= $this->baseUrl() ?>/admin/verifiers">Verifiers</a>
  <img src="<?= $this->baseUrl() ?>/images/icons/bullet_go.png" width="16" height="16" class="icon"/>&nbsp;<a href="<?= $this->baseUrl() ?>/admin/publishing">Plugins For Approval [<b style="color:red;"><?= $this->toBePublished ?></b>]</a>
  <img src="<?= $this->baseUrl() ?>/images/icons/bullet_go.png" width="16" height="16" class="icon"/>&nbsp;<a href="<?= $this->baseUrl() ?>/admin/plugin-list">All Plugins</a>
  <img src="<?= $this->baseUrl() ?>/images/icons/bullet_go.png" width="16" height="16" class="icon"/>&nbsp;<a href="<?= $this->baseUrl() ?>/admin/misc">Misc Admin Stuff</a>
  <img src="<?= $this->baseUrl() ?>/images/icons/bullet_go.png" width="16" height="16" class="icon"/>&nbsp;<a href="<?= $this->baseUrl() ?>/admin/logs">Log viewer</a>
  <img src="<?= $this->baseUrl() ?>/images/icons/bullet_go.png" width="16" height="16" class="icon"/>&nbsp;<a href="<?= $this->baseUrl() ?>/admin/verifiers-activity">Verifiers activity</a>
  <img src="<?= $this->baseUrl() ?>/images/icons/bullet_go.png" width="16" height="16" class="icon"/>&nbsp;<a href="<?= $this->baseUrl() ?>/admin/featured">Featured Plugins</a>
</div>