#!/bin/sh
#                 Sun Public License Notice
# 
# The contents of this file are subject to the Sun Public License
# Version 1.0 (the "License"). You may not use this file except in
# compliance with the License. A copy of the License is available at
# http://www.sun.com/
# 
# The Original Code is NetBeans. The Initial Developer of the Original
# Code is Sun Microsystems, Inc. Portions Copyright 1997-2004 Sun
# Microsystems, Inc. All Rights Reserved.

#
# resolve symlinks
#

PRG=$0

while [ -h "$PRG" ]; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '^.*-> \(.*\)$' 2>/dev/null`
    if expr "$link" : '^/' 2> /dev/null >/dev/null; then
	PRG="$link"
    else
	PRG="`dirname "$PRG"`/$link"
    fi
done

progdir=`dirname "$PRG"`

if [ -f "$progdir"/../etc/netbeans.conf ] ; then
    . "$progdir"/../etc/netbeans.conf
fi

if [ -f /etc/netbeans.conf ] ; then
    . /etc/netbeans.conf
fi

args="$@"

userdir=${netbeans_default_userdir}
while [ $# -gt 0 ] ; do
    case "$1" in
        --userdir) shift; if [ $# -gt 0 ] ; then userdir=$1; fi
            ;;
    esac
    shift
done

if [ -f "${userdir}"/etc/netbeans.conf ] ; then
    . "${userdir}"/etc/netbeans.conf
fi

if [ -z "$netbeans_clusters" ] ; then
    netbeans_clusters="$progdir/../nb4.0:$progdir/../ide4"
    if [ -d "$progdir/../extra" ]; then
        netbeans_clusters="$netbeans_clusters:$progdir/../extra"
    fi
fi

if [ ! -z "$netbeans_extraclusters" ] ; then
    netbeans_clusters="$netbeans_clusters:$netbeans_extraclusters"
fi

case "`uname`" in
    Darwin*)
        "$progdir"/../platform4/lib/nbexec \
            --jdkhome "$netbeans_jdkhome" \
            -J-Dcom.apple.mrj.application.apple.menu.about.name=NetBeans \
            -J-Xdock:name=NetBeans \
            "-J-Xdock:icon=$progdir/../nb4.0/netbeans.icns" \
            --branding nb \
            --clusters "$netbeans_clusters" \
            --userdir "${userdir}" \
            -J-Dnetbeans.importclass=org.netbeans.upgrade.AutoUpgrade \
            ${netbeans_default_options} \
            $args
        ;;
    *)
        "$progdir"/../platform4/lib/nbexec \
            --jdkhome "$netbeans_jdkhome" \
            --branding nb \
            --clusters "$netbeans_clusters" \
            --userdir "${userdir}" \
            -J-Dnetbeans.importclass=org.netbeans.upgrade.AutoUpgrade \
            ${netbeans_default_options} \
            $args
        ;;
esac
