#ifndef EXITCODES_H
#define	EXITCODES_H

#ifndef FS_COMMON_H
#error fs_common.h MUST be included before any other file
#endif

#define FAILURE_LOCKING_MUTEX 1
#define FAILURE_UNLOCKING_MUTEX 2
#define WRONG_ARGUMENT 3
#define FAILURE_GETTING_HOME_DIR 4
#define FAILURE_CREATING_STORAGE_SUPER_DIR 5
#define FAILURE_ACCESSING_STORAGE_SUPER_DIR 6
#define FAILURE_CREATING_STORAGE_DIR 7
#define FAILURE_ACCESSING_STORAGE_DIR 8
#define FAILURE_CREATING_TEMP_DIR 9
#define FAILURE_ACCESSING_TEMP_DIR 10
#define FAILURE_CREATING_CACHE_DIR 11
#define FAILURE_ACCESSING_CACHE_DIR 12
#define NO_MEMORY_EXPANDING_DIRTAB 13
#define FAILED_CHDIR 14
#define FAILURE_OPENING_LOCK_FILE 15
#define FAILURE_LOCKING_LOCK_FILE 16

#endif	/* EXITCODES_H */

