<?php $this->placeholder('footer')->captureStart() ?>

<div class="fo f1">
    <h2>Contacts</h2>
    <p class="kon"> <strong>Branch Prague</strong><br />
        Skretova 12<br />
        100 00  Prague 1<br />
        <br />
    </p>
    <p class="kon"> <strong>Branch Prague</strong><br />
        V parku 2308/8<br />
        140 00  Prague 4<br />
        <br />
    </p>
    <p class="kon"> <strong>Headquarters</strong><br />
        Oracle Pkwy<br />
        Redwood City, CA 94065<br />
        <br />
    </p>
    <div class="cleaner"></div>
</div>
<div class="fo f2">
    <a href="http://netbeans.org" target="_blank" title="Go to NetBeans homepage">
        <img src="/images/netbeans-logo-2.png" width="100px" alt="NetBeans" />
    </a>
</div>
<div class="fo f3">
    <h2>Copyright</h2>
    <p>2010 &copy; Copyright<br />
        Oracle corp.<br />
        All rights reserved<br /><br />
    </p>
</div>

<?php $this->placeholder('footer')->captureEnd() ?>
