<?php
/*
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 *
 * Copyright 2011 Oracle and/or its affiliates. All rights reserved.
 *
 * Oracle and Java are registered trademarks of Oracle and/or its affiliates.
 * Other names may be trademarks of their respective owners.
 *
 * The contents of this file are subject to the terms of either the GNU
 * General Public License Version 2 only ("GPL") or the Common
 * Development and Distribution License("CDDL") (collectively, the
 * "License"). You may not use this file except in compliance with the
 * License. You can obtain a copy of the License at
 * http://www.netbeans.org/cddl-gplv2.html
 * or nbbuild/licenses/CDDL-GPL-2-CP. See the License for the
 * specific language governing permissions and limitations under the
 * License.  When distributing the software, include this License Header
 * Notice in each file and include the License file at
 * nbbuild/licenses/CDDL-GPL-2-CP.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the GPL Version 2 section of the License file that
 * accompanied this code. If applicable, add the following below the
 * License Header, with the fields enclosed by brackets [] replaced by
 * your own identifying information:
 * "Portions Copyrighted [year] [name of copyright owner]"
 *
 * If you wish your version of this file to be governed by only the CDDL
 * or only the GPL Version 2, indicate your decision by adding
 * "[Contributor] elects to include this software in this distribution
 * under the [CDDL or GPL Version 2] license." If you do not indicate a
 * single choice of license, a recipient has the option to distribute
 * your version of this file under either the CDDL, the GPL Version 2 or
 * to extend the choice of license to its licensees as provided above.
 * However, if you add GPL Version 2 code and therefore, elected the GPL
 * Version 2 license, then the option applies only if the new code is
 * made subject to such option by the copyright holder.
 *
 * Contributor(s):
 *
 * Portions Copyrighted 2011 Sun Microsystems, Inc.
 */

echo $this->doctype();
?>
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="en-US">
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=7" />
        <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <meta http-equiv="content-language" content="en-US"/>
        <title>Rent-a-Flat - NetBeans sample!</title>
        <meta name="keywords" content="flat, rental, home, low prices" />
        <meta name="description" content="Sample Zend framework project for NetBeans" />
        <meta name="author" content="Oracle corp." />
        <meta name="copyright" content="(c) 2010 Oracle" />
        <meta name="robots" content="all,index,follow" />
        <meta name="revisit-after" content="14 day" />
        <meta name="expires" content="never" />
        <meta name="cache-control" content="no-cache" />
        <meta http-equiv="pragma" content="no-cache" />
        <link href="/css/cssweb.css" media="screen" rel="stylesheet" type="text/css" />
        <script src="/js/jquery.js" type="text/javascript"></script>
        <script src="/js/function.js" type="text/javascript"></script>

    </head>
    <body>
        <div id="bodyimg">
            <div id="pagebox">
                <div id="top">
                    <h2><a href="<?php echo $this->url(array("controller" => "index", "action" => "index"), null, true) ?>" 
                           title="Go to Homepage">
                            <img src="/images/netbeans-logo.gif" height="93" alt="Logo - Rent A Flat" /></a>
                        <span>
                            Rent-a-Flat with NetBeans <br /> 
                            Zend Framework Sample <br /> 
                            brought to you by <br /> 
                            <b>PHP NetBeans Dev Team!</b>
                        </span>
                    </h2>
                </div>
                <?php echo $this->placeholder('menu'); ?> <?php echo $this->layout()->content ?> <?php echo $this->placeholder('footer'); ?>
            </div>
        </div>
    </body>
</html>