<?php
echo $this->doctype();
?>
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="en-US">
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=7" />
        <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <meta http-equiv="content-language" content="en-US"/>
        <title>Rent-a-Flat - NetBeans sample!</title>
        <meta name="keywords" content="flat, rental, home, low prices" />
        <meta name="description" content="Sample Zend framework project for NetBeans" />
        <meta name="author" content="Oracle corp." />
        <meta name="copyright" content="(c) 2010 Oracle" />
        <meta name="robots" content="all,index,follow" />
        <meta name="revisit-after" content="14 day" />
        <meta name="expires" content="never" />
        <meta name="cache-control" content="no-cache" />
        <meta http-equiv="pragma" content="no-cache" />
        <link href="/css/cssweb.css" media="screen" rel="stylesheet" type="text/css" />
        <script src="/js/jquery.js" type="text/javascript"></script>
        <script src="/js/function.js" type="text/javascript"></script>

    </head>
    <body>
        <div id="bodyimg">
            <div id="pagebox">
                <div id="top">
                    <h2><a href="<?php echo $this->url(array("controller" => "index", "action" => "index"), null, true) ?>" 
                           title="Go to Homepage">
                            <img src="/images/netbeans-logo.gif" height="93" alt="Logo - Rent A Flat" /></a>
                        <span>
                            Rent-a-Flat with NetBeans <br /> 
                            Zend Framework Sample <br /> 
                            brought to you by <br /> 
                            <b>PHP NetBeans Dev Team!</b>
                        </span>
                    </h2>
                </div>
                <?php echo $this->placeholder('menu'); ?> <?php echo $this->layout()->content ?> <?php echo $this->placeholder('footer'); ?>
            </div>
        </div>
    </body>
</html>