/*
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 *
 * Copyright 2009 Sun Microsystems, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of either the GNU
 * General Public License Version 2 only ("GPL") or the Common
 * Development and Distribution License("CDDL") (collectively, the
 * "License"). You may not use this file except in compliance with the
 * License. You can obtain a copy of the License at
 * http://www.netbeans.org/cddl-gplv2.html
 * or nbbuild/licenses/CDDL-GPL-2-CP. See the License for the
 * specific language governing permissions and limitations under the
 * License.  When distributing the software, include this License Header
 * Notice in each file and include the License file at
 * nbbuild/licenses/CDDL-GPL-2-CP.  Sun designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Sun in the GPL Version 2 section of the License file that
 * accompanied this code. If applicable, add the following below the
 * License Header, with the fields enclosed by brackets [] replaced by
 * your own identifying information:
 * "Portions Copyrighted [year] [name of copyright owner]"
 *
 * If you wish your version of this file to be governed by only the CDDL
 * or only the GPL Version 2, indicate your decision by adding
 * "[Contributor] elects to include this software in this distribution
 * under the [CDDL or GPL Version 2] license." If you do not indicate a
 * single choice of license, a recipient has the option to distribute
 * your version of this file under either the CDDL, the GPL Version 2 or
 * to extend the choice of license to its licensees as provided above.
 * However, if you add GPL Version 2 code and therefore, elected the GPL
 * Version 2 license, then the option applies only if the new code is
 * made subject to such option by the copyright holder.
 *
 * Contributor(s):
 *
 * Portions Copyrighted 2009 Sun Microsystems, Inc.
 */

package org.netbeans.modules.kenai.ui.project;

import java.awt.Cursor;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.io.IOException;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.SwingUtilities;
import org.netbeans.modules.kenai.api.KenaiException;
import org.openide.util.Exceptions;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;
import org.openide.util.ImageUtilities;
import org.netbeans.api.settings.ConvertAsProperties;
import org.netbeans.modules.kenai.api.Kenai;
import org.netbeans.modules.kenai.api.KenaiFeature;
import org.netbeans.modules.kenai.api.KenaiProject;
import org.netbeans.modules.kenai.api.KenaiService;
import org.openide.util.RequestProcessor;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
    dtd="-//org.netbeans.modules.kenai.ui.project//kenaiProject//EN",
    autostore=false
)
public final class kenaiProjectTopComponent extends TopComponent implements PropertyChangeListener {

    RequestProcessor SingleDataRequestProcessor = new RequestProcessor("KENAI_SINGLE_IMG_REQUEST_PROCESSOR", 1, true); //NOI18N
    RequestProcessor SingleImageRequestProcessor = new RequestProcessor("KENAI_SINGLE_DATA_REQUEST_PROCESSOR", 1, true); //NOI18N

    private RequestProcessor.Task loadingImageTask = null;
    private RequestProcessor.Task loadingDynamicContentTask = null;

    /** path to the icon used by the component and its open action */
    static final String ICON_PATH = "org/netbeans/modules/kenai/ui/resources/kenai-small.png"; //NOI18N

    private static final String PREFERRED_ID = "kenaiProjectTopComponent"; //NOI18N
    private static final String KENAI_URL = Kenai.normalizeUrl(System.getProperty("kenai.com.url", "https://kenai.com")); //NOI18N

    private static kenaiProjectTopComponent inst = null;
    private KenaiProject instProj = null;

    public kenaiProjectTopComponent() {
        initComponents();
    }

    public kenaiProjectTopComponent(KenaiProject proj) {
        initComponents();
        setName(proj.getDisplayName());
        setToolTipText(NbBundle.getMessage(kenaiProjectTopComponent.class, "HINT_kenaiProjectTopComponent")); //NOI18N
        setIcon(ImageUtilities.loadImage(ICON_PATH, true));
        instProj = proj;
        addSpecificContent(proj);
        Kenai.getDefault().addPropertyChangeListener(this);
    }

    public static synchronized kenaiProjectTopComponent getDefault() {
        if (inst == null) {
            inst = new kenaiProjectTopComponent();
        }
        return inst;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        containingPanel = new javax.swing.JPanel();
        generalDetailsPanel = new javax.swing.JPanel();
        projectDescription = new javax.swing.JPanel();
        webLinks = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        wwwLabel = new javax.swing.JLabel();
        wikiLabel = new javax.swing.JLabel();
        downloadsLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        projectsDetailsHeader = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        projectsDetailsText = new javax.swing.JTextArea();
        imagePanel = new javax.swing.JPanel();
        projectImage = new javax.swing.JLabel();
        dynamicContentsPanel = new javax.swing.JPanel();
        dynamicContentPane = new javax.swing.JTabbedPane();

        setLayout(new java.awt.BorderLayout());

        containingPanel.setBackground(new java.awt.Color(255, 255, 255));
        containingPanel.setMinimumSize(new java.awt.Dimension(820, 475));
        containingPanel.setPreferredSize(new java.awt.Dimension(820, 489));

        generalDetailsPanel.setBackground(java.awt.SystemColor.controlHighlight);
        generalDetailsPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        generalDetailsPanel.setMaximumSize(new java.awt.Dimension(20800, 200));
        generalDetailsPanel.setMinimumSize(new java.awt.Dimension(800, 200));
        generalDetailsPanel.setPreferredSize(new java.awt.Dimension(800, 200));
        generalDetailsPanel.setLayout(new java.awt.BorderLayout());

        projectDescription.setOpaque(false);
        projectDescription.setLayout(new java.awt.BorderLayout());

        webLinks.setOpaque(false);
        webLinks.setPreferredSize(new java.awt.Dimension(496, 70));

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(kenaiProjectTopComponent.class, "kenaiProjectTopComponent.jLabel1.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(kenaiProjectTopComponent.class, "kenaiProjectTopComponent.jLabel2.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(kenaiProjectTopComponent.class, "kenaiProjectTopComponent.jLabel3.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(wwwLabel, org.openide.util.NbBundle.getMessage(kenaiProjectTopComponent.class, "kenaiProjectTopComponent.wwwLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(wikiLabel, org.openide.util.NbBundle.getMessage(kenaiProjectTopComponent.class, "kenaiProjectTopComponent.wikiLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(downloadsLabel, org.openide.util.NbBundle.getMessage(kenaiProjectTopComponent.class, "kenaiProjectTopComponent.downloadsLabel.text")); // NOI18N

        org.jdesktop.layout.GroupLayout webLinksLayout = new org.jdesktop.layout.GroupLayout(webLinks);
        webLinks.setLayout(webLinksLayout);
        webLinksLayout.setHorizontalGroup(
            webLinksLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(webLinksLayout.createSequentialGroup()
                .addContainerGap()
                .add(webLinksLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel1)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel2)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel3))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(webLinksLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(wwwLabel)
                    .add(wikiLabel)
                    .add(downloadsLabel))
                .addContainerGap(416, Short.MAX_VALUE))
        );

        webLinksLayout.linkSize(new java.awt.Component[] {jLabel1, jLabel2, jLabel3}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        webLinksLayout.setVerticalGroup(
            webLinksLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(webLinksLayout.createSequentialGroup()
                .add(webLinksLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(webLinksLayout.createSequentialGroup()
                        .add(wwwLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(wikiLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(downloadsLabel))
                    .add(webLinksLayout.createSequentialGroup()
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel3)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        webLinksLayout.linkSize(new java.awt.Component[] {downloadsLabel, jLabel1, jLabel2, jLabel3, wikiLabel, wwwLabel}, org.jdesktop.layout.GroupLayout.VERTICAL);

        projectDescription.add(webLinks, java.awt.BorderLayout.PAGE_END);

        jPanel1.setOpaque(false);

        projectsDetailsHeader.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(projectsDetailsHeader, org.openide.util.NbBundle.getMessage(kenaiProjectTopComponent.class, "kenaiProjectTopComponent.projectsDetailsHeader.text")); // NOI18N

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setOpaque(false);

        projectsDetailsText.setBackground(java.awt.SystemColor.controlHighlight);
        projectsDetailsText.setColumns(20);
        projectsDetailsText.setEditable(false);
        projectsDetailsText.setLineWrap(true);
        projectsDetailsText.setRows(3);
        projectsDetailsText.setWrapStyleWord(true);
        projectsDetailsText.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setViewportView(projectsDetailsText);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(projectsDetailsHeader)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(projectsDetailsHeader)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addContainerGap())
        );

        projectDescription.add(jPanel1, java.awt.BorderLayout.CENTER);

        generalDetailsPanel.add(projectDescription, java.awt.BorderLayout.CENTER);

        imagePanel.setOpaque(false);
        imagePanel.setPreferredSize(new java.awt.Dimension(200, 200));

        projectImage.setBackground(new java.awt.Color(255, 255, 255));
        projectImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(projectImage, org.openide.util.NbBundle.getMessage(kenaiProjectTopComponent.class, "kenaiProjectTopComponent.projectImage.text")); // NOI18N
        projectImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        projectImage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        projectImage.setIconTextGap(0);
        projectImage.setOpaque(true);

        org.jdesktop.layout.GroupLayout imagePanelLayout = new org.jdesktop.layout.GroupLayout(imagePanel);
        imagePanel.setLayout(imagePanelLayout);
        imagePanelLayout.setHorizontalGroup(
            imagePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(imagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(projectImage, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addContainerGap())
        );
        imagePanelLayout.setVerticalGroup(
            imagePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(imagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(projectImage, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                .addContainerGap())
        );

        generalDetailsPanel.add(imagePanel, java.awt.BorderLayout.WEST);

        dynamicContentsPanel.setOpaque(false);
        dynamicContentsPanel.setLayout(new java.awt.BorderLayout());
        dynamicContentsPanel.add(dynamicContentPane, java.awt.BorderLayout.CENTER);

        org.jdesktop.layout.GroupLayout containingPanelLayout = new org.jdesktop.layout.GroupLayout(containingPanel);
        containingPanel.setLayout(containingPanelLayout);
        containingPanelLayout.setHorizontalGroup(
            containingPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, containingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(containingPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, dynamicContentsPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 803, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, generalDetailsPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 803, Short.MAX_VALUE))
                .addContainerGap())
        );
        containingPanelLayout.setVerticalGroup(
            containingPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(containingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(generalDetailsPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(dynamicContentsPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane2.setViewportView(containingPanel);

        add(jScrollPane2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel containingPanel;
    private javax.swing.JLabel downloadsLabel;
    private javax.swing.JTabbedPane dynamicContentPane;
    private javax.swing.JPanel dynamicContentsPanel;
    private javax.swing.JPanel generalDetailsPanel;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel projectDescription;
    private javax.swing.JLabel projectImage;
    private javax.swing.JLabel projectsDetailsHeader;
    private javax.swing.JTextArea projectsDetailsText;
    private javax.swing.JPanel webLinks;
    private javax.swing.JLabel wikiLabel;
    private javax.swing.JLabel wwwLabel;
    // End of variables declaration//GEN-END:variables

    /**
     * Obtain the kenaiProjectTopComponent instance.
     */
    public static synchronized kenaiProjectTopComponent getInstance(KenaiProject forProject) {
        boolean hard = false;
        if (inst == null){
            inst = new kenaiProjectTopComponent(forProject);
            hard = true;
        } else if (!inst.instProj.equals(forProject)) {
            hard = true;
        }
        inst.reinitialize(forProject, hard);
        inst.setName(forProject.getDisplayName());
        return inst;
    }

    @Override
    public int getPersistenceType() {
        return TopComponent.PERSISTENCE_NEVER;
    }

    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    Object readProperties(java.util.Properties p) {
        return null;
    }

    void writeProperties(java.util.Properties p) {
        
    }

    @Override
    protected String preferredID() {
        return PREFERRED_ID;
    }

    public void reinitialize(final KenaiProject proj, boolean hardReinit) {
        // must be here because of the specific contents
        instProj = proj;
        SwingUtilities.invokeLater(new Runnable() {

            public void run() {
                // reset header and description text
                projectImage.setIcon(null);
                projectsDetailsHeader.setText(proj.getDisplayName());
                try {
                    projectsDetailsText.setText(proj.getDescription().replaceAll("\r?\n", " ").replaceAll("\r", " ")); //NOI18N
                    projectsDetailsText.setCaretPosition(0);
                } catch (KenaiException ex) {
                    Exceptions.printStackTrace(ex);
                }
            }
        });

        // load image on the background
        if (loadingImageTask != null && !loadingImageTask.isFinished()) {
            loadingImageTask.cancel();
        }
        loadingImageTask = SingleImageRequestProcessor.post(new Runnable() {
            
            public void run() {
                try {
                    URL imgUrl = new URL(proj.getImageUrl());
                    final Icon ico = ImageUtilities.image2Icon(ImageIO.read(imgUrl));
                    SwingUtilities.invokeLater(new Runnable() {

                        public void run() {
                            projectImage.setIcon(ico);
                        }
                    });
                } catch (IOException ex) {
                    Exceptions.printStackTrace(ex);
                }
            }
        });

        // Refresh the dynamic content
        if (hardReinit) {
            if (loadingDynamicContentTask != null && !loadingDynamicContentTask.isFinished()) {
                loadingDynamicContentTask.cancel();
            }
            loadingDynamicContentTask = SingleDataRequestProcessor.post(new Runnable() {

                public void run() {
                    int tabCount = dynamicContentPane.getTabCount();
                    for (int i = 0; i < tabCount; i++) {
                        if (dynamicContentPane.getComponentAt(i) instanceof RefreshableContentPanel) {
                            ((RefreshableContentPanel) dynamicContentPane.getComponentAt(i)).resetContent(instProj);
                        }
                    }
                }
            });
        }

        // Set default text for labels with www, wiki and downloads
        wwwLabel.setText(NbBundle.getMessage(kenaiProjectTopComponent.class, "kenaiProjectTopComponent.wwwLabel.text")); //NOI18N
        wikiLabel.setText(NbBundle.getMessage(kenaiProjectTopComponent.class, "kenaiProjectTopComponent.wikiLabel.text")); //NOI18N
        downloadsLabel.setText(NbBundle.getMessage(kenaiProjectTopComponent.class, "kenaiProjectTopComponent.downloadsLabel.text")); //NOI18N

        // Set label for www - make it link
        wwwLabel.setText(String.format("<html><a href=\"blank\">%s</a></html>", KENAI_URL + proj.getWebLocation().getPath())); //NOI18N
        wwwLabel.setToolTipText(KENAI_URL + proj.getWebLocation().getPath());
        wwwLabel.setCursor(new Cursor(Cursor.HAND_CURSOR));
        URLClickListener.selfRegister(wwwLabel, proj.getWebLocation());
        KenaiFeature[] _features = null;
        try {
            _features = proj.getFeatures();
        } catch (KenaiException ex) {
            Exceptions.printStackTrace(ex);
        }
        if (_features == null) {
            return;
        }
        for (int i = 0; i < _features.length; i++) {
            final KenaiFeature kenaiFeature = _features[i];
            if (kenaiFeature.getType().equals(KenaiService.Type.DOWNLOADS)) {
                // Set label for downloads - make it link
                downloadsLabel.setText(String.format("<html><a href=\"blank\">%s</a></html>", KENAI_URL + kenaiFeature.getWebLocation().getPath())); //NOI18N
                downloadsLabel.setToolTipText(KENAI_URL + kenaiFeature.getWebLocation().getPath());
                downloadsLabel.setCursor(new Cursor(Cursor.HAND_CURSOR));
                URLClickListener.selfRegister(downloadsLabel, kenaiFeature.getWebLocation());
            } else if (kenaiFeature.getType().equals(KenaiService.Type.WIKI)) {
                // Set label for wiki - make it link
                wikiLabel.setText(String.format("<html><a href=\"blank\">%s</a></html>", KENAI_URL + kenaiFeature.getWebLocation().getPath())); //NOI18N
                wikiLabel.setToolTipText(KENAI_URL + kenaiFeature.getWebLocation().getPath());
                wikiLabel.setCursor(new Cursor(Cursor.HAND_CURSOR));
                URLClickListener.selfRegister(wikiLabel, kenaiFeature.getWebLocation());
            }
        }
    }

    private void addSpecificContent(KenaiProject proj) {
        dynamicContentPane.add(NbBundle.getMessage(kenaiProjectTopComponent.class, "MSG_COMMUNICATE"), new ForumsAndMailingListsPanel(proj)); //NOI18N
    }

    public void propertyChange(PropertyChangeEvent evt) {
        if (evt.getPropertyName().equals(Kenai.PROP_LOGIN)) {
            reinitialize(instProj, true);
        }
    }

}
