/*
 * ExportPanel.java
 *
 * Created on March 24, 2006, 2:55 PM
 */

package org.netbeans.bluej.export;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.SwingUtilities;
import org.openide.filesystems.FileUtil;

/**
 *
 * @author  mkleint
 */
public class ExportPanel extends javax.swing.JPanel {
    
    /** Creates new form ExportPanel */
    public ExportPanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        lblWarning = new javax.swing.JLabel();
        lblFolder = new javax.swing.JLabel();
        txtFolder = new javax.swing.JTextField();
        btnFolder = new javax.swing.JButton();

        lblWarning.setText("<html>This will convert your BlueJ project to become a full-fledged Netbeans J2SE project. <p>\nIn the process, <b>it will copy your sources to the new destination and split classes and tests</b>. \n<p>Additionally, any libraries defined within BlueJ will be copied to the project's libs subdirectory.</html>");
        lblWarning.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lblFolder.setText("New Project Location :");

        btnFolder.setText("Browse...");
        btnFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFolderActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lblWarning, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(lblFolder)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(txtFolder, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(btnFolder)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(lblWarning, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 101, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblFolder)
                    .add(btnFolder)
                    .add(txtFolder, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(156, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFolderActionPerformed
                JFileChooser chooser = new JFileChooser();
                FileUtil.preventFileChooserSymlinkTraversal(chooser, null);
                chooser.setFileSelectionMode( JFileChooser.DIRECTORIES_ONLY );
                chooser.setMultiSelectionEnabled( false );
                int option = chooser.showOpenDialog( SwingUtilities.getWindowAncestor( this ) ); // Sow the chooser
                if (txtFolder.getText().length() > 0) {
                    chooser.setCurrentDirectory(new File(txtFolder.getText().trim()));
                }
                if ( option == JFileChooser.APPROVE_OPTION ) {
                    
                    File file = chooser.getSelectedFile();
                    txtFolder.setText(FileUtil.normalizeFile(file).getAbsolutePath());
                }

    }//GEN-LAST:event_btnFolderActionPerformed
    
    public File getNewProjectLocation() {
        return new File(txtFolder.getText());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFolder;
    private javax.swing.JLabel lblFolder;
    private javax.swing.JLabel lblWarning;
    private javax.swing.JTextField txtFolder;
    // End of variables declaration//GEN-END:variables
    
}
