OBJS := $(OBJFILES:%=$(OBJ_DIR)/%)
DEPS := $(OBJS:%.o=%.d)
DEPFLAGS := -MMD -MP

clean_deps:
	$(RM) $(DEPS)

$(OBJS): $(OBJ_DIR)/%.o: $(SRC_DIR)/%.c | $(OBJ_DIR)
	$(COMPILE.c) $(DEPFLAGS) -MF $(@:%.o=%.d) -o $@ $<

-include $(DEPS)
